### ISSUE TITLE
[epic] [auth] User authorization for actions

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#108]
This epic will address user authorization, a user is elegible for certain action or not.

## Implementation steps

There will be seperate implementaion for different actions as logic for each 

* [x] Create an authorization.py that encapsulates authorization logic
* [x] List of roles with actions #110  
* [x] Create `has_permission / is_allowed` #111 
* [x] Refactor API permissions to use this (may want to create a decorator?)

## Background

We have a standard access control matrix with 3 axes:

- Actions: CREATE, READ, WRITE, DELETE, PURGE 
- Entities (object): User, Publisher, Package, Package Resource, …  
- Users: a user or type of user 

**Introducing Roles**

It can be inefficient to list every user for every object. It is also cumbersome to manage in terms of business processes. For example:

1. Many users in an organization get same set of privileges because of their position in the organization.
2. We want to change the permissions associated with a certain level in the organization and to have those permissions changed for all people in that level
3. A user may change level frequently (ex. user may get promoted)

So we create roles

- Per object roles e.g. Package Owner 
- Per system roles e.g. System Administrator 
- A list or algorithm for assigning Users =&gt; Roles 

Access control algorithm: `is_allowed(user, entity, action tuple)`

- For this user: what roles do they have related to this entity and the system? 
- Given those roles: what actions do they have: UNION[role](Actions) 
    - Note: it would get more complex if some roles deny access. E.g. Role: Spammer might mean you are denied action to posting etc. Right now we don’t have that issue. 
- Is the desired action in that set? 

### Actions

*Note: not an exhaustive list*

- Package 
    - Package::Read 
    - Package::Create 
    - Package::Delete 
    - Package::Undelete 
    - Package::Purge 
    - Package::Update 
    - Package::Tag 
- Publisher 
    - Publisher::Create 
    - Publisher::AddMember 
    - Publisher::RemoveMember 
    - Publisher::Read 
- …  

Roles

- Package 
    - Owner  =&gt; all actions 
    - Editor =&gt; Read, Update, Delete (not Purge) 
    - Viewer  =&gt; Only read 
- Publisher 
    - Owner =&gt; all actions on Publisher 
        - =&gt; PackageOwner 
    - Editor =&gt; PublisherViewMemberList, PublisherUpdate, PublisherDelete 
        - =&gt; PackageEditor 
    - Viewer =&gt; Read 
- System 
    - LoggedIn =&gt; [Package::Create, Publisher::Create] 
    - All =&gt; Package::Read on public packages 
    - Sysadmin =&gt; all actions 

Business roles:

- Publisher Owner 
    - =&gt; [Access Control] PublisherOwner 
- Publisher Member 
    - =&gt; PublisherEditor 
- (Logged in) User 
    - =&gt; System::LoggedIn 
- Visitor

**NOTE**: business roles and authorization roles are distinct. Of course, in implementing access control we will use the business logic inherent in business roles. However, business roles are **not** explicitly present in the access control system.

### Algorithm

```
# package here is passed as a Package instance Package(53) not as a string.
# raises question of how to indicate class of all packages.
def is_allowed(rufus, Package(53), 'Package::Delete')
    roles = get_roles(rufus, Package(53))
    for role in roles:
        if role in get_actions(role):
		return True
    return False

def get_roles(rufus, package):
	roles = []
	If rufus is sysadmin:
		roles.append(Roles.Sysadmin)
	if package.__type__ = ‘Package’:
		if rufus is Owner Package.Owner (a Publisher):
			return [Package::Owner]
		elif rufus is Owner Package.Owner (a Publisher):
			return [Package::Editor]
		else: # in future when private packages this would be different
                    return [Package::Viewer]
	return roles

# Role List
{
	“Sysadmin”: [ action1, action2]
	“Package::Owner”: {}
}

# Could do as a matrix. 
# For now the simple dict approach is probably sufficient
	Role: A, B, C
Action X	Y, N, N
Action Y	Y, Y, N
...
```

---

## Future - API

Do we need an API for auth. Not sure we do since used entirely internally. Maybe useful in frontend if you want to decide whether to show an option to do something. Overall doubtful we need this atm.

Base: `/api/authz/` OR `/api/auth/access` (tbd)

API to check auth:

```
GET  BASE/{user}/{entity-id}/{action}

e.g.

../this-user/Package::53/Package::READ

Returns: { status: true | false }
```

API to grant and revoke access:

```json
POST /api/auth/access 
DELETE /api/auth/access
Body : {"user_id": <id>, "actions": [<action names>]}
```

**Comment by subhankarb** [comment]
Fixed
