### ISSUE TITLE
Improve line chart on data package view page

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#118]
## Desired features

* Elegant and beautiful
* Zoomable
* Download current chart

Later

* Configure chart to add new lines or change to log axis

## Preliminary required work

* [x] Review existing libraries - #106 
* [x] Make a choice about which library we use
  * [x] Compare vega/vega-lite vs plotly (vs maybe bokeh)
  * [x] Make a choice - we prefer plotly for line graphs but will support vega[-lite] configs and vega option
* [x] Spec out in detail how this is going to work - e.g. how we go from a datapackage.json and its data to a graph
  * In progress - see below. More to come
  * Some decisions
    * Focus on a vega-lite style for defining views => will NOT support recline style config going forward (work to be done in converting across data packages in #129 or we will need a shim to support those for now)
    * ...
* [x]  Decide whether we do react js refactor now or not and how to sequence that with this change.
  * YES: given the refactor we need to do to have the graph code right we may as well do react at the same time.

## Implementation Plan

* [x] Get vega-lite working #136
* [x] Refactor JS to use react #137 
  * [x] Do a react view for handsontable ... 
  * [x] Integrate graphs and use data from API
* [x] Recline view spec support #143 
* [x] Plotly support #138

Next: recline spec conversion (if we want that - could be trivial)

**Comment by pwalsh** [comment]
FYI I've used https://github.com/reactjs/react-chartjs in, for example https://github.com/frictionlessdata/data-quality-dashboard/blob/master/app/ui/scripts/components/charts/publisher.js

**Comment by rgrp** [comment]
Next steps:

* [ ] Compare vega/vega-lite vs plotly (vs maybe bokeh)
* [ ] Decide whether we do react js refactor now or not and how to sequence that with this change

**Comment by rgrp** [comment]
Updated description and moving to 19 dec milestone. In 5 dec milestone we completed research but did not get to start work on the upgrade.

**Comment by anuveyatsu** [comment]
I was working with React and Vega-lite over CDN and in that case it is ok. But when tried with npm install and build with browserify / webpack, I had problems. Seems it is common issue for Vega: https://github.com/vega/vega/wiki/Vega-and-Browserify
But I could not find info about vega-lite. I tried this Vega’s one and it did not work.

**Comment by anuveyatsu** [comment]
There is a third-party package to work with React and Vega-lite, which makes it super easy: https://github.com/anuveyatsu/dpr-js-with-react-vega-lite

**Comment by rufuspollock** [comment]
FIXED. Pretty much! I think there may be some remaining issues with vega style views but recline + plotly is working.
