### ISSUE TITLE
OKI Code review

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/dpr-api#121]
- [x] Please provide a stable URL to a staging version of the app (stable enough to be more or less up every day) 
   - #123 and maybe #124 
- [x] As far as I can see, [zappa](https://github.com/Miserlou/Zappa) does not require one to add zappa-specific code into a codebase itself. However, our [codebase has many references to Zappa](https://github.com/frictionlessdata/dpr-api/blob/master/app/mod_api/controllers.py#L443). Why? If you need to inject one or a few Zappa variables, then do it as a context processor so such vars can be set cleanly in one place, rather then as part of function signatures throughout the codebase
   - #127 
- [ ] FYI Flask has a built-in CLI for management scripts, making the old [Flask migrate](https://github.com/frictionlessdata/dpr-api/blob/master/manager.py#L23) package obsolete.
  - **need to be discussed**
- [x] Please don't have [fake/dummy data](https://github.com/frictionlessdata/dpr-api/blob/master/manager.py#L50) in the actual codebase. What is this function here for anyway?
  - *This for pushing initial demo data into system*
- [ ] More [dummy](https://github.com/frictionlessdata/dpr-api/blob/master/manager.py#L80)  [data](https://github.com/frictionlessdata/dpr-api/blob/master/manager.py#L62) [here](https://github.com/frictionlessdata/dpr-api/blob/master/manager.py#L91) makes me wonder if these commands work for general usage? Why are they in the codebase and not, for example, in the test suite?
- [x] Please use [Postgres 9.5 or 9.6](https://github.com/frictionlessdata/dpr-api/blob/master/.travis.yml#L14)
  - *When we first deployed 9.5 was not available in travis. Right now it is there. Will do it #126*
- [ ] Is there a valid reason, such as a dependency that we don't need, to not [support Python 3](https://github.com/frictionlessdata/dpr-api/blob/master/tests/test_basics.py#L19)?
   - **need to be discussed**
- [x] There are a [range of roles here](https://github.com/frictionlessdata/dpr-api/blob/master/tests/utils/test_authorization.py#L58). I need some documentation on users, publishers and roles please.
   - *There is some detailed doc in #108 . But if we need that in code as docstring will add #161*
- [ ] Tests that are ["not 404"](https://github.com/frictionlessdata/dpr-api/blob/master/tests/mod_site/test_site.py#L163) do not test that a page exists ;)
- [x] All new users are [`OWNERS`](https://github.com/frictionlessdata/dpr-api/blob/master/tests/mod_site/test_site.py#L311)?
  - *For every new user a publisher is created of which it is the owner*
- [x] These [bitstore tests](https://github.com/frictionlessdata/dpr-api/blob/master/tests/mod_api/test_models.py#L19) as in the models test module. it is a bit confusing.
  - *There exists a model named```BitStore``` , it has all s3 related operations. Thats why it is in ```test_model.py``` file*
- [x] Small issue, but way repeat info across inheriting classes in config? e.g.: [here](https://github.com/frictionlessdata/dpr-api/blob/master/app/config.py#L36) and [here](https://github.com/frictionlessdata/dpr-api/blob/master/app/config.py#L84). Related, if there is a development config, why is there not a production one too?
   - #126
- [x] Related to similar notes [here](https://github.com/frictionlessdata/dpm-py/issues/41), I need a good explanation of the interaction between auth0 as a provider, our use of JWT, and the fact that we also have email/password.
   - **See #162**
   - https://github.com/frictionlessdata/dpr-docs/issues/14
- [x] We need more docstrings. For example, what actually is [Catalog](https://github.com/frictionlessdata/dpr-api/blob/master/app/mod_site/models.py#L9)? I know data packages and this problem space in generally really well, but looking at the fields on the model, I'm not sure what catalog objects actually are. #126 
- [ ] Is [this](https://github.com/frictionlessdata/dpr-api/blob/master/app/mod_api/models.py#L28) a validate function for a data package? if yes, why like this, and if not, what is it?
  - *It was a very early implementation. Opening #125*
- [x] [`PUT`](https://github.com/frictionlessdata/dpr-api/blob/master/app/mod_api/controllers.py#L22) and not `POST` - why?
  - *PUT is always used for creating and POST for update and modify. Although we can update through this api, but wanted to specify that this api used for creation*
- [x] [this](https://github.com/frictionlessdata/dpr-api/blob/master/app/mod_api/controllers.py#L187) pushes metadata to a database, but [this](https://github.com/frictionlessdata/dpr-api/blob/master/app/mod_api/controllers.py#L136) only purges the filesystem and not the database
  - *[this](https://github.com/frictionlessdata/dpr-api/blob/master/app/mod_api/controllers.py#L168) line delete data packages from filesystem and [this](https://github.com/frictionlessdata/dpr-api/blob/master/app/mod_api/controllers.py#L169) line deletes data from DB*
- [ ] We don't yet have any search functionality at all, and some other API methods from the requirements are not implemented ([ref.](https://docs.google.com/document/d/11M9FOh30hgLKiXyXLhfkVc8faqf22x6dKllXeuMG2lM/edit#heading=h.4zt2rkcfg6yk)).
  - *We are not implementing again the product requirements but against the priority user stories which were more limited.*
- [ ] We don't [cache resources](https://docs.google.com/document/d/11M9FOh30hgLKiXyXLhfkVc8faqf22x6dKllXeuMG2lM/edit#heading=h.xip7okknkaw) if the DP has remote resources
  - *We don't. Ditto to last point. Nice to have but not on the critical path we identified :wink:*
- [ ] While the client expects the server to validate data in data packages, I can't find any functionality where the server does this validation.
  - *Another item where this is not on the immediate roadmap. No issue for that for that reason but we do have a user story.*

**Comment by pwalsh** [comment]
About docs for users/permissions/roles being in https://github.com/frictionlessdata/dpr-api/issues/108 well, it is a closed issue :). Please add the documentation to the README so it is discoverable, and also add docstrings.

About documenting `Catalog` - I gave catalog as an example, but the whole codebase needs useful docstrings, so https://github.com/frictionlessdata/dpr-api/issues/126 does not (adequately) address this.

About PUT and POST - your usage is at odds with the general usage of PUT and POST. Here is a [simple description](http://stackoverflow.com/questions/630453/put-vs-post-in-rest). I don't care for sticking to conventions for convention's sake, but in this case, it makes little sense to deviate from pretty clear usage of PUT and POST in rest API design.

About purging, you are right, I missed that line. However, it made me realise that it is possible to purge one or the other and thereby lose the sync between bitstore and DB.

Search and caching need to be done. They are really foundational aspects of the registry. We can discuss when the other major points are addressed.

**Comment by rufuspollock** [comment]
Moving to Backlog. A good amount *was* done in 19 Dec sprint and remaining items will get done at different times.

**Comment by rufuspollock** [comment]
FIXED. Mainly fixed. Main outstanding items are large things that are about major features (and Search is in progress).

We can def revisit this in next round of reviewing.
