### ISSUE TITLE
Deploy staging app with stable url

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#123]
* [x] Finish dpr-deploy
  * [x] Have someone test it (e.g. @zelima)
* [x] Deploy app
* [x] Document

Not part of this issue but needed to do this:

* [x] Get a nice domain / URL for it - #121

**Comment by subhankarb** [comment]
Fixed
