### ISSUE TITLE
A live stable staging site with core data packages imported

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#134]
* [x] Deploy app with stable url #123 
* [x] Automate deployment of staging app #124 
* [x] Import core datasets from data.okfn.org #129

**Comment by subhankarb** [comment]
Fixed
