### ISSUE TITLE
[super] API for Publish

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/dpr-api#2]
- [x] Auth token generator - `/api/auth/token` #3
- [x] Create / update datapackage with new metadata `POST /api/package/{publisher}/{package}` #4 (data now in BitStore)
  - [x] Ingest from BitStore to MetaStore (not API but internal event logic) #8 
- [x] Authorize file upload to BitStore `POST /api/auth/bitstore_upload`. #5
- [x]  TODO: ?? - really not sure about this `POST /api/package/{publisher}/{package}/finalize` #41
## Diagram

<img src="https://docs.google.com/drawings/d/1lZdZtDOvEAm8MVpdVsLaOHc5da6Sxtg-cQ34WtemKZo/pub?w=1153&h=735" />

**Comment by rgrp** [comment]
Based on comment from @pwalsh in https://github.com/frictionlessdata/dpr-api/issues/8#issuecomment-258070638 looks like we **do** want a `finalize` method.

**Comment by rgrp** [comment]
FIXED. All subissues now done! Hurrah!
