### ISSUE TITLE
Data Package Search

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#200]
TODO: short description / user story.

## Tasks

API

* [x] API controller exists with search endpoint - just returns all packages unsorted or default sort order or most recent first (by created!) - #198 
* [x] Filter by publisher `?publisher=xxx` (no support for generic `?q=...` syntax #211
* [x] Search in titles - simple "like" support (? - may not need if we do next item first) #227

UI
- [x] Add dedicated search page #221 

For later - in API:
* [ ] Full text search of titles and README (and description) #218 
* [ ] Sort support ...

### API

- [x] Able to search data package filter by publisher
- [x] Able to search data package by title

### UI

- [x] Dedicated search page
- [x] Able to see list of data package
- [x] From publisher page search data packages of that publisher

---

# Background and Analysis

## Original User Story

As a Consumer I want to search data packages so that I can find the ones I want
- Search results should provide enough information to help a user decide whether to dig further e.g. title, short description 
    -  For future when we have it: [number of downloads], stars etc
- Minimum viable search (based on implementation questions)
    - Filter by publisher
    - Free text search against title
    - Description could be added if we start doing actual scoring as easy to add additional fields
    - Scoring would be nice but not essential

### Key features we need to support:

* Filter by: publisher
  * User would be a nice addition (?)
* Search within title
  * README an optional extra
* Results: return data packages
* Search by profile: No support for this at the moment.

Flow

* Front page (when logged out) has search form and there is search form in the navbar (logged in) - can also visit `/search` at any time and it has a search form
  * Search form is very simple: just free text
  * QU: TODO do we need typeahead ??
* Search takes user to `/search` where results are displayed
  * In this page we also has a search form in the page [in navbar - NO]. For modifying the search
* When you click on the data package link (heading and maybe button too) you are redirected to the /{publihser}/{package} page.

QUESTION: should we include searching for publishers (at the same time e.g. in a side bar of page. ANS: no, not atm)

### Tasks

* Search API + test
* Search UI + test
  * Uses react on `/search` page
 
### API

```javascript=
GET {api}/search/package

Options:

- q = query option e.g. "gdp publisher:world-bank"
- sort (and order): defaults to most recently created

GET {api}/search/package?q=...
```

Response

```javascript=
{
    // suggest "items" or "results" to be generic
    "packages": [
        {
            "name": "package1",
            "description": "",
            "private": true
        },
        {
        
        }
    ],
    "total": 152,
    "page":1,
    "limit": 10
}
```

TODO:

* pagination (and limit)
* limiting access to private packages (do we just exclude entirely or try and actually figure out what this user has access to?)

#### Scoring and text search in title and description {1}

We need [SQLAlchemy-Searchable](http://sqlalchemy-searchable.readthedocs.io/en/latest/index.html)

What would query look like?

```python=
# added column name and readme to be searchable
# we can add weights to the search result just by adding weights.
# Here name will have heigher weight that readme.
search_vector = db.Column(TSVectorType('name', 'readme'),
        weights={'name': 'A', 'readme': 'B'})

# query for 'abc'
query = session.query(Package)
query = search(query, 'abc')

# query for 'abc' and publisher:core
query = session.query(Package).join(Publisher).filter(Publisher.name='core')
query = search(query, 'abc', sort=True)
```

#### Simplest possible - no scoring) {0.5 }

No changes just use like query to search the pattern.

```sql=
-- for query abc 
SELECT * FROM package WHERE title LIKE '%abc%'
-- query for 'abc' and publisher:core 
SELECT * FROM package WHERE title LIKE '%abc%' AND Publisher.name = "xyz";
```

### UI changes and Search Results Page {2d}

UI changes:

* navbar ?
* search page?
* front page?

Do we want a separate search page atm? Do we just use this API in building the publisher profile?

Search Page:

```
/search
```
**navbar** search box is the way to go.

#### React Components

- SearchPage
    - PackagePreview [reuse from publisher page]
    - PublisherPreview

**Comment by pwalsh** [comment]
@subhankarb implementation section says the following:

    Registered User visits their Dashboard and has a prominent highlighted section saying "Invite users to join {DPR}"

And a list of following points. Why is this needed to implement search?

**Comment by pwalsh** [comment]
@rufuspollock why use Postgres search and not a decent search index like Elasticsearch? 

IIRC, even the most basic cases of UK/US spelling variation will not be possible with Postgres. I can't imagine that development time is greatly impacted by choosing one or the other....

**Comment by subhankarb** [comment]
@pwalsh for the first comment. Sorry was a typo.

**Comment by rufuspollock** [comment]
@pwalsh development time will be impacted by using ES vs Postgres in terms of deployment - it is yet another piece of infrastructure. Happy to do it, but in my experience it will have some impact (e.g. we have to make sure data gets written somewhere else, have to set this up for testing etc etc)

**Comment by Fak3** [comment]
> ## Acceptance Criteria
> From publisher page search data packages of that publisher

As I understand this is not a priority, and even more - it does not require search api at all. The filter can be implemented purely in js, filtering list of packages stored in the frontend (that was fetched when page opened).

**Comment by rufuspollock** [comment]
For @subhankarb to do:

* Search input in the search page (and make navbar search smaller)
* Search heading: "Search" on search page
* Show query in search input on search page

**Comment by subhankarb** [comment]
FIXED.
