### ISSUE TITLE
API_KEY should be configurable in .env file

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-api#206]
API_KEY is a secret used in the backend to encode\decode jwt tokens. Right now it is hardcoded to "dpr-api-key" in the app/config.py. It should instead be a secret string, configurable in the .env file.

I also propose to give more informative name, for ex. "JWT_SEED"

## Tasks

- [x] Change API_KEY name to JWT_SEED.
- [x] Set `app.secret_key` value to  JWT_SEED.
- [x] Make JWT_SEED hard coded for test and development config, and variable in staging config.
- [x] Change README.

**Comment by rufuspollock** [comment]
+1

**Comment by zelima** [comment]
FIXED ` JWT_SEED` set as env variable
