### ISSUE TITLE
Package Search API filter by publisher

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#211]
Filter by publisher ?q=xxx publisher:{name}

## Tasks

- [x] Write one failing test.
- [x] Parse the query string to generate filtering options [here it is by publisher]
- [x] Create the filtering query and get data from db.
