### ISSUE TITLE
Integration dpr-js into deployment automatedly

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#212]
We have front end module in https://github.com/frictionlessdata/dpr-js . It creates final build named bundle.js and commits it to github. This is error prone as we forgets to build bundle.js before commit sometimes. 

Solution: Build bundle.js automatically while deploying dpr-api with dpr-deploy.

## Tasks

- [x] Make react resource file load with flask. Need to configure webpack. 
- [x] Remove bundle.js from dpr-js repo and add in gitignore.
- [x] Upgrade deploy script to generate bundle while deploying.
- [x] Run flask app locally in WSGI Containers. [Some times when multiple request comes in flask IO error is noticed. So it is recomended to run in wsgi container. We are using gevent]
- [x] Update dpr-api readme how to generate bundle.js if running locally.
- [x] Remove vendor and js directory from dpr-api/app/static (separate - these are obsoleted by dpr-js now)

**Comment by pwalsh** [comment]
npm has a post install hook for that purpose.

**Comment by Fak3** [comment]
> Remove vendor and js directory from dpr-api/app/static.

Isn't it separate issue? Am I right, that we are dropping it because we moved all js to dpr-js repo, and it is not related to automated bundling?

**Comment by rufuspollock** [comment]
@Fak3 strictly you are correct and I mentioned this to @subhankarb yesterday. Suggest you split out a separate issue and move that item out.

**Comment by subhankarb** [comment]
FIXED.
In dpr-api: https://github.com/frictionlessdata/dpr-api/pull/215
In dpr-js: https://github.com/frictionlessdata/dpr-js/pull/93
Also fix the dpr-deploy with task for installing npm packages and build.
