### ISSUE TITLE
Migrate all frontend pages to JS from Flask

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#214]
We are moving the front-end to be a single-page-app in React. We need to move existing Flask pages to React.

## Tasks:

- [ ] Basic scaffolding
- [x] Migrate datapackage details page https://github.com/frictionlessdata/dpr-js/issues/67
- [ ] Migrate home page
- [ ] Migrate sign-in/signup https://github.com/frictionlessdata/dpr-js/issues/61
- [ ] Migrate user dashboard https://github.com/frictionlessdata/dpr-js/issues/89
- [x] Implement publisher dashboard page. Partly done with https://github.com/frictionlessdata/dpr-js/issues/96
- [ ] Convert theme to run in React
- [ ] Switch Flask to serve our JS SPA for all URLs other than API etc

## Issues:

- When we navigate from `/` to `/:publisher` it works. Because at '/' it calls flask app, gets static files the all navigation works inside react-router . But it we directly put `/:publisher` this api directly call flask app and we get 404. #219

**Comment by rufuspollock** [comment]
@subhankarb can you add **all** the pages we needed to migrate including the ones we've done.

**Comment by subhankarb** [comment]
INVALID.
As we are moving back to MPA(flask) we do not have to implement this.
