### ISSUE TITLE
[js] Render specific page when called exact URL

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#219]
When called `/` url flask server serves the assets. Then if we navigate to `/:publisher` page we go to publisher page. But when we directly put `/:publisher` we get 404 as flask app does not have that route. 

## Solution:
We have to pattern match all url that do not match `/api/*` and pass the path to react. Then we can push the path to react-router [ `browser_history.push(path)`  ] so that that specific path will open.

## Tasks:

- [ ] Add flask controller to server assets when path is not `/api/*`
- [ ] In dpr-js index.html add ``` window.__DATA__.url``` to get url path from flask
- [ ] In dpr-js index.js add ``` browserHistory.push(window.__DATA__.url);``` before render react app.

**Comment by subhankarb** [comment]
INVALID.
As we are move back to MPA. We do not have to implement this.
