### ISSUE TITLE
Implement Search page

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#221]
We need to implement dedicated search page.

## Implementation:

- URL structure for search page would be /search?q=term
Page structure
- We can reuse the PackageList from Publisher component to view datapackages

## Tasks:

- [x] Mock search page in a google drawing [layout](https://docs.google.com/drawings/d/1dj2ZUV5SJgBtBd58ArSsojEraXQkLJUc5ZC9RI5VRcU/edit?userstoinvite=subhankar.biswas@atomatic.net&ts=5899b0dd&actionButton=1)
- [x] Create search page
  - [x] Test
  - [x] Controller `/search`
  - [x] Template - can reuse *some* components from publisher page (e.g. list of packages) - inspiration from npm registry
- [x] Other UI changes
  - [x] Modify navbar with search form in base.html
- [x] PR review

**Comment by subhankarb** [comment]
FIXED.
Fixed with https://github.com/frictionlessdata/dpr-api/pull/228

**Comment by rufuspollock** [comment]
@subhankarb for these times of major UI items it would be nice to link to the page or feature on the site as part of your closing of the issue.
