### ISSUE TITLE
Revert to Multi Page App

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#222]
We want to move back from current approach of single page to perviously created flask multi page app.

## Tasks:

- [x] Revert back to old HTML
  - [x] Datapackage view page [old dataset.html]
  - [x]  Home Page
- [x] Modify back dpr-js to work with previous dpr-api structure
  - [x] Update webpack to work with dpr-api MPA
  - [x] Update dpr-api dataset snippet method to work with 
- [x]  Convert React to HTML pages
  - [x] Publisher page - convert
  - [x] Added in place search option.

**Comment by rufuspollock** [comment]
@subhankarb please don't change estimates during sprints unless there is a **very** special reason 😉 - o/w we don't get a sense of how good our original estimates were.

Also is this now FIXED?

**Comment by subhankarb** [comment]
FIXED.
Fixed with pull requests
- https://github.com/frictionlessdata/dpr-api/pull/226
- https://github.com/frictionlessdata/dpr-api/pull/223
- https://github.com/frictionlessdata/dpr-js/pull/104
