### ISSUE TITLE
Improve Sign In/ Sign out process

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#231]
We use jwt for tracking user's signed in or signed out status. 
Every time user goes to home page index.html page returns back. Then we check token stored in local storage. Then send token to server for expiration check. Then new page returns back from server.

Problem:  
- We were sending post message to `/`to check jwt expiration time, and if expired from server we redirect to logout.html from server.
- If logged in and if refresh page. It logged in state goes away. as local storage token check is in index.html page.

Solution: We check the validity of JWT from client itself. And remove redirect from server. And check token in local store before loading new html page. So the logic for token check should be base.html which every other html page extends.

This will also solve #191 

## Tasks:

- [x] Write jwt validity method in client side.
- [x] Remove the redirection logic from server.
- [x] Add login/logout button in navbar. So that it can be accessible from  any page.

**Comment by Fak3** [comment]
The client can't check the validity of jwt token itself, as she does not know server's secret jwt seed.

**Comment by Fak3** [comment]
The only way to remove extra client-server roundtrip is to pass jwt in cookies.

**Comment by Fak3** [comment]
The issue #191 can be handled by the client, as she only needs to check the expiration time fo the token, not the validity. But in general we will have to switch to cookies, so it will solve #191 automatically.

**Comment by subhankarb** [comment]
@Fak3 sorry it is not the validity. It is the expiration time :).

**Comment by rufuspollock** [comment]
@subhankarb there is still no clear description of the problem from the user perspective. What do they experience here that is problematic? If this is not a user problem what is the technical issue?

**Comment by subhankarb** [comment]
@rufuspollock 
- Problem 1: Refresh problem
   - go to staging.datapackaged.com.
   - Login --> Dashboard
   - Refresh. We are not logged in. 

- Problem 2: Login Problem.
   - Go to staging.datapackaged.com/core/{package} .. If i want to login. There is no login button

**Comment by subhankarb** [comment]
FIXED.
Fixed with pull req https://github.com/frictionlessdata/dpr-api/pull/235
