### ISSUE TITLE
Production site set up

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#234]
We have to setup the site in production environment - http://datapackaged.com/

## Tasks

- [x] ~~Run automated deploy script~~
  - [x] ~~Set up infrastructure (AWS stuff, Auth0) (automated)~~
  - [x] ~~Logging (by zappa)~~
- [ ] ~~Generate certificates~~
  - [x] ~~Certificate for S3 cloudfront~~
  - [ ] ~~Certificate for API Gateway custom domain~~

As we switched now to use heroku none of steps above are necessary

- [x] run deploy script https://gitlab.com/datopian/datahub-deploy
- [x] setup cloudflare
- [x] run verify script

**Comment by rufuspollock** [comment]
@subhankarb write out step by step what we do to setup the SSL stuff.

**Comment by subhankarb** [comment]
@rufuspollock Facing issue with naked domain. I found some way to resolve this. Steps to fix this

- Deploy fully hosted domain
- Remove WWW:
- Set up a .htaccess file in said directory to redirect the naked domain to www.datapackaged.com

**Comment by rufuspollock** [comment]
@subhankarb can you describe naked domain issue more precisely.

I also emphasize that we don't want to redirect datapackaged.com to www.datapackaged.com -- we just want to use datapackaged.com.

**Comment by subhankarb** [comment]
The way we could point domain to cloudfront is like:
- Add a custom DNS record to datapackaged.com:
  - set Name [keep blank for `datapackaged.com`]
  - set type [CNAME]
  - set Value [cloud front distribution] 
But the problem is for naked domain `datapackaged.com` we can not set `CNAME`.
So how can we point `datapackaged.com` to `cloudfront`.
AWS `route53` has option `alias` to point domain to any distribution. But in dreamhost i am not able to find any option.

**Comment by rufuspollock** [comment]
@subhankarb can you clarify in your steps by step *where* things happen. e.g. "Add a custom DNS record ..." -- **where** do you do this.

**Comment by zelima** [comment]
FIXED website is up https://datapackaged.com
