### ISSUE TITLE
[ux] New Theme and Styling for site

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#245]
Using [Bootstrap 3.3.7 in Sass](https://github.com/twbs/bootstrap-sass) we need to build a new theme for the site. Initial thoughts can be found [here](https://docs.google.com/presentation/d/1iOuChAEGS0_5f6S7BI3nlTZ_icPxR1esoPEtR0uX5ck/edit#slide=id.g146da424a9_0_0)

## Tasks

* [x] Design and mockups for theme (including front page mockup) - #280
* [x] First pass on a front page #279 
  * [x] customize Bootstrap Sass according to mockups
  * [x] create HTML document using customized CSS output
* ~Data page~
  * ~Mock up https://github.com/frictionlessdata/dpr-api/issues/281~
  * ~Implement https://github.com/frictionlessdata/dpr-api/issues/282~

**Comment by anuveyatsu** [comment]
See https://github.com/anuveyatsu/dpr-new-theme

**Comment by rufuspollock** [comment]
@anuveyatsu general layout looks good. Purple is a no-go 😉  - for now could we use the old image background at the top of the page. In terms of general colouring your original mockups with the green were better so i'd go with that as the general colour rather than green.

Then please move forward asap to implement.

**Comment by anuveyatsu** [comment]
CLOSING as Data Page part now moved into #332
