### ISSUE TITLE
Converge with openspending conductor API

### ISSUE THREAD

**Issue by Fak3** [frictionlessdata/dpr-api#249]
Subissues to address sepecific changes to be done:
* [x] #248 Create `/api/bitstore/authorize_upload` endpoint
* [x] #250 Use 'Auth-Token' instead of 'Authentication' header
* [x] #251 Openspending-compatible upload finalization api.

In dpmpy:
- [x] Change request header for authorization https://github.com/frictionlessdata/dpm-py/issues/84
- [x] Change upload file process https://github.com/frictionlessdata/dpm-py/issues/83
- [x] Modify publish method  https://github.com/frictionlessdata/dpm-py/issues/82

**Comment by rufuspollock** [comment]
FIXED.
