### ISSUE TITLE
[ux] Misc UX improvements as 2 March 2017

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#259]
The below lists some bugs and improvements found out in the current version of the website https://staging.datapackaged.com

## Tasks

* [x] Navbar search box do not respond on enter button - #261
* [x] Data Package view page fixes
  * [x] Layout like old site with resource previews interspersed in page
    * [x] server side - #262
    * [x] dpr-js - https://github.com/frictionlessdata/dpr-js/issues/119
    * [x] Update back-end for front-end changes in 119
       * [x] update to latest dpr-js code
       * [x] have one `div` element for graphs
       * [x] have as many `div` elements as resources for handsontable
   * [x] Short description at top of page includes non-parsed markdown - #270
* [x] Graph improvements
  * [x] The graph do not show unit/name in y axis https://github.com/frictionlessdata/dpr-js/issues/124
* [ ] Table improvements - https://github.com/frictionlessdata/dpr-js/issues/125

**Comment by rufuspollock** [comment]
FIXED. We'd done this last sprint but were keeping open for minor part of last item. Given we don't have a clear resolution on that (date rendering in tables) I'm closing.
