### ISSUE TITLE
Replacing auth0 with simple github login

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#268]
We have Auth0 as out authentication system. We want to implement OAuth authentication replacing Auth0.

### Tasks

* [x] Implement flask-oauthlib 
  * [x] Create github app [datopian account] for getting key and secret 
  * [x] We can directly use openspending's code for flask-oauthlib.
* [x] Refactor publisher creation flow
  * Change or fix urls for the flow
  * Fixing tests
* User model change
  * [x] Remove column `auth0-id` from user table
  * [x] Add a column about source (e.g. github) and source id (e.g. github id)
* [x] Change `manager.py` script 
* [x] Change the dpr-deploy script

## Acceptance Criteria

* [ ] You can login to the site with github (and github only for now)
* [ ] Your email and key profile information is saved locally and used e.g. in setting gravatar
* [ ] You are redirected to dashboard after signup / login
* [ ] A publisher is created for you with your username

**Comment by rufuspollock** [comment]
@subhankarb just flagged we also need to fix the `dpr-deploy` script.

**Comment by rufuspollock** [comment]
@subhankarb you'll also need to remember to change deploy config on next deploy (probably when we merge dpr-js stuff in frictionlessdata/dpr-js#119)

**Comment by rufuspollock** [comment]
Reopening:

**Sign in experience**

The sign in / sign up buttom takes you to a github page immediately with no context. You need at least some intervening page or modal that is our "sign up" page that says something like: "Sign up with your github account".
  * See hackmd.io for a good example.
  * Note hackmd.io just have "sign in" (no sign up) which right now may be all we need

I tried signing in and got:

```
{
"error_code": "GENERIC_ERROR",
"message": "'NoneType' object has no attribute 'encode'"
}
```

**Comment by subhankarb** [comment]
@rufuspollock about the error `'NoneType' object has no attribute 'encode'`. I did not handled for private email. If the user make the email private we can not get it. And code is not handled for empty email address.

**Comment by pwalsh** [comment]
goodtables.io has a signin flow for GitHub, for your reference, which deals with inaccessible emails, seeing as we are still somehow avoiding copy/paste of a tested and working OS auth implementation.

BTW, as the GitHub auth API does not guarantee that it provides emails, you obviously can't rely on sending welcome emails and so on. I still contend that this is not a problem, and is in fact quite common in oauth backed signin flows.

**Comment by subhankarb** [comment]
@pwalsh thanks. I just found it. and FIXED.

**Comment by rufuspollock** [comment]
@pwalsh is there a ref for the goodtables implementation.

**Comment by pwalsh** [comment]
https://github.com/frictionlessdata/goodtables.io/blob/master/goodtablesio/auth.py

And blueprint for handling flow.

**Comment by subhankarb** [comment]
@rufuspollock added github icon in signin button 
<img width="275" alt="screen shot 2017-03-10 at 11 00 42 pm" src="https://cloud.githubusercontent.com/assets/2178361/23805858/95cbfb88-05e5-11e7-9848-837f1975cdfc.png">

**Comment by rufuspollock** [comment]
FIXED.
