### ISSUE TITLE
Files in bits FileStore have wrong Content-Type

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#273]
e.g. datapackage.json has binary/octet-stream should be json. Try:

```
curl -I https://bits.staging.datapackaged.com/metadata/core/cpi-us/_v/latest/datapackage.json
```

**Why is this a problem**: 
- when you click on Metadata in the views page the datapackage.json downloads rather than being viewable in the browser.

Want right content type for JSON and for everything else set text/plain 
 

## Problem

When we upload any file in AWS S3 the file type by default set to `binary/octet-stream`. But we want proper file type.

In dpr-api https://github.com/frictionlessdata/dpr-api/blob/master/app/package/models.py#L124  default file type has been set to `binary/octet-stream` if file type is not given.

## Solution

Add `Content-Type` while publishing data to S3

## Tasks

- [x] What file type we want to set for what file?
  - We want to set application/json for datapackage.json, and for other `text/plain`. We want to set all file type to`text/plain` as it avoids security risks (e.g. somone uploading html with malicious JS in it and then users opening that file as html).
- [x] Do we want to set file type in dpmpy or dpr-api?
  - dpr-api already has the provision to take file type and add it to pre-signed post call. So we do not have to change any thing in dpr-api. 
  - [gobble](https://github.com/openspending/gobble/blob/master/gobble/fiscal.py#L280) sets this in cli. So we already has the file type options while obtaining the pre-signed post.
  - HOWEVER: best option is to enforce text/plain on server for all files
     - Good for security
     - Incredibly simple
     - No risk that a client forgets to set the file type!

## Acceptance Criteria:

- [ ] In S3 all data should be of type `text/plain` and datapackage.json should be of type `application/json`

**Comment by subhankarb** [comment]
@rufuspollock I updated the description with analysis
