### ISSUE TITLE
New Theme and Front Page Layout

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#278]
We would like to redesign Data Package Registry front page to make it look more elegant and aligned with the brand identity of the site (frictionless: simple, powerful and elegant).

A new design was created (see [mockup](https://drive.google.com/a/atomatic.net/file/d/0B7ucLyXmP0n2SmdNTUtqR1B1Mk0/view?usp=sharing)).

Now we need to implement it using provided images and information(fonts, colours, etc.).

### Context and problems

> Start implementing in the temporary github repo so others can preview in gh-pages.

## Analysis

1. Create a basic html document according to the mockup - should have header, jumbotron and section for the mockup's second part.
2. Customize Bootstrap-Sass
3. Include all required assets
4. Work on additional stylings for assets
5. Move to DPR-API

## Tasks

Overall estimate: [8h]

* [x] Create basic html document [1.5h]
  * [x] header element [0.5h]
    * [x] navbar
    * [x] logo
  * [x] jumbotron element [0.5h]
    * [x] background image
    * [x] main and secondary text
    * [x] frontground images
    * [x] sign up button
  * [x] section element [0.5h]
    * [x] searchbox
    * [x] grid for text with boxes
    * [x] elephant with numbers image
* [x] Customize Bootstrap-Sass [1h]
  * [x] fonts [0.5h]
  * [x] necessary variables - colours, backgrounds [0.5h]
* [x] Include all assets and work on sylings [4h]
  * [x] work on sizing and placing [2h]
  * [x] work on general layout staylings [2h]
* [x] Move to DPR-API [1.5h]
  * [x] integrate with DPR-API templates [1h]
  * [x] replace old stylesheets with new one [0.5h]

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-api/pull/279
Everything from the issue's description was achieved. Now we are using a new layout for the front page:
![image](https://cloud.githubusercontent.com/assets/17809581/23854730/ee853a4e-081c-11e7-98ae-dac5ee7a6c3f.png)

**Comment by subhankarb** [comment]
The issues found:
- Search box is not working.
- Signup in front page not working.
- Navbar 
  - Does not have search box.
  - Publish data tab does not work.
  - Find data tab does not work.
  - `Data package` tab does not work.
  - `navbar-header` class should point to `/` instead of `#`

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-api/pull/285 and https://github.com/frictionlessdata/dpr-api/pull/286
