### ISSUE TITLE
Limit option in search

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#294]
As a Publisher I want to see all my packages or search all packages via API

## Solution

pagination (ultimately). Short term solution: limit option with large limit values

## Tasks 

* [x] introduce limit keyword for search API with max value of 1000 (default of 20) `?limit={integer}` (cast to integer and if exception set to 20)
  * [x] Write test first!
* [x] change search page and set max to 1000 for now
