### ISSUE TITLE
Datapackage delete and purge commands are failing

### ISSUE THREAD

**Issue by subhankarb** [frictionlessdata/dpr-api#295]
When we try to execute commands `delete` and `purge` server is responding with error code 500.

## Errors

The error we are getting for `delete` command is `ERROR Error 500. Failed to change status`
The error we are getting for `purge` command is `ERROR Error 500. Failed to delete from db`

When we tag one datapackage we have multiple row for datapackage as  unique key constrain in package table is (package name, publisher name, tag). So if we have 2 tags `latest` and `0.1`
we will end up with 2 rows in Package table.

While deleting the packages we were calling sql-alchemy's `one()` method. That is why it was throwing exception.

## Tasks

- [x] replicate on main site
- [x] replicate against localhost:5000.
- [x] Write failing tests for multiple tags.
- [x] Add failing test for delete and purge command
- [x] Update Package.delete_data_package method
- [x] Update Package.change_status method
- [x] Change Package Model
  - [x] Fix failing tests for Package model
- [x] Add PackageTag Model
- [x] Change search function as it search on descriptor. And descriptor moves to package_tag table

## Acceptance Criteria:

- [ ] Can delete package with multiple tags.
- [ ] Can purge package with multiple tags.
- [ ] Can republish package after purge.

## Analysis

The code for delete and update status is like this

```python=0
data = Package.query.join(Publisher). \
        filter(Publisher.name == publisher_name,
               Package.name == package_name).one()
data.status = status
db.session.add(data)
db.session.commit()
```

This code was written before implementing tagging so we were fetching one datapackage and delete.

The table structure for package is like this:

```python=
class Package(db.Model):
    """
    This class is DB model for storing package data
    """
    __tablename__ = "package"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    name = db.Column(db.TEXT, index=True)
    version = db.Column(db.TEXT, index=True, default='latest')
    descriptor = db.Column(db.JSON)
    status = db.Column(db.Enum(PackageStateEnum, native_enum=False),
                       index=True, default=PackageStateEnum.active)
    private = db.Column(db.BOOLEAN, default=False)
    readme = db.Column(db.TEXT)

    publisher_id = db.Column(db.Integer, ForeignKey('publisher.id'))
    publisher = relationship("Publisher", back_populates="packages",
                             cascade="save-update, merge, delete, delete-orphan",
                             single_parent=True)

    __table_args__ = (
        UniqueConstraint("name", "version", "publisher_id"),
    )
```
`package_name, publisher_name, version` is the unique key. So if we have two version of the package there will be 2 rows.

So our code should be 

```python=0
packages = Package.query.join(Publisher). \
                filter(Publisher.name == publisher_name,
                       Package.name == package_name).all()
for package in packages:
    package.status = status
    db.session.add(package)
db.session.commit()
```
This will update the status for all datapackages.
The same change will fix delete bug also. The code for delete will be
```python=0
packages = Package.query.join(Publisher). \
                filter(Publisher.name == publisher_name,
                       Package.name == package_name).all()
for package in packages:
    package_id = data.id
    meta_data = Package.query.get(package_id)
    db.session.delete(meta_data)
db.session.commit()
```

About the table structure for tagging.
We want to store versions for datapackage so that 
- we can check how datapackage evolve over time
- can download specific version of the datapackage

The data changes between different versions are
- descriptor
- README
- version
- created time for the version

With the current table structure we have to store `status` and `private` multiple times.

A better table structure would be 

```python=0
class Package(db.Model):
    """
    This class is DB model for storing package data
    """
    __tablename__ = "package"

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    name = db.Column(db.TEXT, index=True)
    
    status = db.Column(db.Enum(PackageStateEnum, native_enum=False),
                       index=True, default=PackageStateEnum.active)
    private = db.Column(db.BOOLEAN, default=False)

    publisher_id = db.Column(db.Integer, ForeignKey('publisher.id'))
    publisher = relationship("Publisher", back_populates="packages",
                             cascade="save-update, merge, delete, delete-orphan",
                             single_parent=True)
    tags = relationship("PackageTag", back_populates="package")
    
    __table_args__ = (
        UniqueConstraint("name", "publisher_id"),
    )

class PackageTag(db.Model):

    __tablename__ = 'package_tag'
    
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    created_at = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    tag = db.Column(db.TEXT, index=True, default='latest') # e.g. v0.1 (we would encourage semver)
    tag_description = db.Column(db.Text)  # free text description like a commit message (for the future!)
    descriptor = db.Column(db.JSON)
    readme = db.Column(db.TEXT)
    
    package_id = db.Column(db.Integer, ForeignKey('package.id'))

     
    package = relationship("Package", back_populates="tags",
                             cascade="save-update, merge, delete, delete-orphan",
                             single_parent=True)
                             
    __table_args__ = (
        UniqueConstraint("tag", "package_id"),
    )
    
```

The authorization is for package level. The purge and delete API is already have `Package::Update` authorization.

**Comment by subhankarb** [comment]
@rufuspollock I updated the description with my investigation for failing deletion and purging command.

**Comment by rufuspollock** [comment]
@subhankarb where is the existing test for the delete and purge commands so I can take a look?

From your description this sounds like it also relates to the way we modelled the tag system with a new row for each package -- something we discussed yesterday separately. Can you write up a short analysis of the user story here and the current implementation so we can think about the best way forward.

**Comment by pwalsh** [comment]
```
class Package(Model):
    id = the unique identifier for this package
    latest = PackageTag instance with tag `latest`.
    tags = list of PackageTag instances

    def create(self): class method to create new package tags 
    def update(self, tag): class method to update existing package tags 
    def delete(self, id): class method to delete new package tags

class PackageTag(Model):
    id = can just be tag name
    package = key to Package
    # then .all the normal fields we have for a package
```

?

We need something similar to above to not expose the internals of package tagging directly to the application, and following, to have a simpler interface for managing tags without exposing sql alchemy directly to the application.

It makes it easy to add helper methods to Package like "has multiple tags" and so on

**Comment by rufuspollock** [comment]
Moving to next sprint as incomplete (analysis nearly done - not yet implemented).
