### ISSUE TITLE
Review of user interface

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/dpr-api#298]
- [x] in general, the UI is going in a nice minimal direction, but still quite rough. There are lots of little details that need attention before we expose this to users. I do not refer to "bells and whistles", but the most essential aspects of user feedback and guidance, placement of things, removal of elements that do not belong, etc. **[NOT VALID] Work on UI is in process and no specific action given here.**
  - *AGREED: we know that we have not had resource for much design or UX so far.* Doing in #368 
- [x] the home page needs to have placeholders sorted / content correct
  - *Do you mean featured datapackages and the command line image on front page or ...?* *[moved to #359 ]*
- [x] Credits are missing: OKI, Datopian, Sloan, etc.
  - *WILLFIX - how big a priority is this?* *[moved to #330 ]*
- [x] *[moved to #330 ]* swagger / api spec - recommend we don't consider this v1 yet (I recommend we follow semantic versioning, so we should keep this below v1 for a couple of months at least)
  - *AGREED*
- [x] when I log in I get to the page that shows me how to interact with the command line. However, when I navigate away from this page, I cannot get back again
  - *FIXED: this was a bug arising from #292 and cookie issues and is now fixed in that the dashboard is at / if you are logged in*
- [x] The instructions to install are wrong (I've raised this before). `dpmpy configure` fails with `ERROR No Data Package found at /Users/pwalsh/Code. Did not find datapackage.json at /Users/pwalsh/Code/datapackage.json`
  - *Understood. I agree that data package check should come after configure* [FIXED]
- [x] page on logout needs a little work
  - *OK* *moved to #330*
- [x] after I log in, i have no profile page - no list of my packages (even to show none). In fact, as the CLI docs are wrong, there is nothing I can do at all apart from use the search box
  - *The logic is you are a user not a publisher. I agree that a proper dashboard would be nice -- but it is a whole bunch more work* [probably a part of future improvements and no specific action given]
- [x] *[FIXED in #329 ]* search results page needs work. when no results, there is no reasonable user feedback. when do get results, the visual layout is very confusing.
  - *AGREED. I wanted to roll up UX work here into the further work on the theme.*
- [x] When I go to my own public profile (which I can work out because of URL structure, not because the app can get me there), I get no useful information, no calls to action, no indication i have 0 data packages and that is why it is empty. Also, it does not use my profile pic, but rather the datopian one. Additionally, there is an extra search box that sits in a weird place, and does not work.
  - *Hmmm. One thing this comment indicates is that the distinction between users and publishers may not be very clear. I think the way to address is to show list of your publishers on "your" i.e. the users dashboard.* [TBD]
  - Partly FIXED:
    - [x] it does indicate that a user has 0 packages
    - [x] we're using generic gravatar atm
    - [x] purpose of the search box is to search within a publisher's packages - but we may need to hide it if there is no packages
- [x] Serious random issues on the Data Package Detail pages, due to the way data is being loaded. I can get the browser pane because completely unresponsive for many seconds - presumably this is while doing loading of data for the views, but with the size of the data we are talking about ( I'm testing https://staging.datapackaged.com/core/imf-weo#data ) there is no way we should be getting stop everything experiences like this on the main thread.
  - *INVALID? I'm not able to reproduce this issue. Note that that dataset now does not load with the new strict datapackage-js - see the console log for the error (this is also a massive dataset 1.6Mb CSV* [TBD]
- [x] Also on the above page, on the 2nd file, I still see that weird black box animated under the data table, and the data table is still empty (no content) for the 2nd file. These were issues we discussed last week which were supposed to already be fixed and ready for deploy
  - *INVALID: the black box is a loader gif - a poor choice i know and we will replace (we were trying for something boxy! The reason it gets stuck there is because of error - see previous point*
- [x] *[moved to #332 ]* There is no visual heirarchy between the data tables and the new "field information" tables. it is very confusing to scan and undertand these pages.
  - *AGREED: our theme work got halted after we did the front page due to other items #245 - we plan to return to it.*
- [x] I still do not see any visualisations rendering
  - *Can you give some examples? They work for me e.g. https://staging.datapackaged.com/core/co2-ppm*
- [x] Confusing user actions on this page. Interactions with assets for this DP (resources and descriptor) need to use consistent terminology and actions:
  - [x] metadata button - triggers a download for the DP descriptor - why call it metadata (this is a dp registry, let's keep the terminology consistent)
     - [x] *Naming: This was a copy over from data.okfn.org. Will correct.* see #363  
     - [x] *Downloading: this is a bug that was already identified #273 re mimetype in bitstore. This was fixed 17d ago but only got fixed in staging after we rebuild s3 2d ago*
  - data button - takes user down to the data section of page, where user can view tables, and click "download" for any resources.
    - [x] *This is same as data.okfn.org. I agree it can be improved and have lots of thoughts. But time and tide and battered eggs ...* see #363 
  - [x] Also: is there an issue with media type for the files - why do they all trigger downloads?
    - *See #273*
- [x] Compare the UX of landing on the new site to landing on the old site: http://data.okfn.org/data - we've completely lost the most basic discoverability of core datasets
  - *Well sort of. Once we have featured datasets / publishers back on the front page that should improve. Moreover, as I keep emphasizing consumers of data don't come via your search page they come via google so this does not really matter ...*

**Comment by anuveyatsu** [comment]
FIXED - see corresponding issues from the description.
