### ISSUE TITLE
Tutorial Data Package on Simple Views

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#308]
As a Publisher I want to understand how I can very quickly and easily add a graph (or table) to my data package.

## Acceptance Criteria

* [x] Tutorial data package on site
* [x] Trialled this with a "new" user (e.g. irakli) and he has signed off (with no coaching!)
* [x] Tutorial data package on github

## Tasks

* [x] create a repo with some sample datapackage but without views
* [x] write a README with steps to be taken to display a graph for a new user
* [x] give that tutorial to somebody and make sure he/she can follow the guide without assistance
* [x] publish result on the site
* [x] have a tutorial datapackage on the site with 3 views
  * [x] line graph view
  * [x] bar chart view
  * [ ] (optional) pie chart view - we may not support this yet (in which case supporting pie charts should be a separate issue)
  * [x] README with explanation of datapackage and simple view spec

Tutorial repo - https://github.com/anuveyatsu/tutorial-datapackage
Tutorial datapackage on the site - https://staging.datapackaged.com/anuveyatsu/finance-vix

**Comment by anuveyatsu** [comment]
@rufuspollock some comments regarding view types:
* **line graphs:** working just fine.
* **bar charts:** we need to add plotly module - it is very simple so I will just commit that change into master.
* **pie charts:** we currently cannot render pie charts as in Plotly they require different specification of data - instead of `x` and `y` values we need to pass `values` and `labels`.

Please tell me if I should go implement Pie chart support.

**Comment by rufuspollock** [comment]
@anuveyatsu re pie charts - as just added to tasks: please leave them out here and create a separate issue for supporting them distinct from this item. You can close this item without doing pie charts.

Re the pie charts: don't necessarily go implement. They are generally poor information design so we may not support them.

**Comment by anuveyatsu** [comment]
created issue for pie charts https://github.com/frictionlessdata/dpr-js/issues/146

**Comment by anuveyatsu** [comment]
FIXED see https://staging.datapackaged.com/anuveyatsu/finance-vix and https://github.com/anuveyatsu/tutorial-datapackage

**Comment by zelima** [comment]
FIXED
