### ISSUE TITLE
Vega support for DPR

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#309]
As a Publisher I want to add sophisticated graphs (using Vega) to my data package so that others can see how cool the data is

## Acceptance Criteria

* [x] Instructional data package with examples and an excellent README (in a separate repo)
* [x] Have following as Data Packages with vega views
  * [x] http://vega.github.io/vega-editor/?mode=vega&spec=barley
  * [x] (it has data transform) http://vega.github.io/vega-editor/?mode=vega&spec=choropleth
  * [x] https://vega.github.io/vega-editor/?mode=vega&spec=lifelines
  * [x] https://vega.github.io/vega-editor/?mode=vega&spec=driving

## Tasks

* [x] https://github.com/frictionlessdata/dpr-js/issues/142
* [x] https://github.com/frictionlessdata/dpr-js/issues/144
* [x]  Instructional data package: https://github.com/anuveyatsu/datapackage-vega-view
* [x] Demo datapackage in the site https://staging.datapackaged.com/anuveyatsu/barley
* [x] https://github.com/frictionlessdata/dpr-js/issues/148

**Comment by anuveyatsu** [comment]
@rufuspollock  in the second example graph we have 2 resources for the view. At the moment we can render only with one resource per view. I think we should create a separate issue or even an epic to be able to render a view using several resources.

So I took another example http://vega.github.io/vega-editor/?mode=vega&spec=driving with a single resource.

**Comment by rufuspollock** [comment]
@anuveyatsu please add the driving item to the acceptance criteria here and move the other multi-resource item to the new multiple resource support item as a nice example.

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-api/commit/212ef5ee9d8a6345a817e9456cb595fad1fa9b9a

Last PR in https://github.com/frictionlessdata/dpr-js/pull/149
