### ISSUE TITLE
Plotly spec support for DPR

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#318]
In the DPR we would like to have a support for Plotly graph spec.
Very similar to https://github.com/frictionlessdata/dpr-api/issues/309

## Acceptance criteria

* [ ] Demo datapackage on the site
* [ ] Demo datapckage on the repo
* [ ] render https://plot.ly/javascript/choropleth-maps/#usa-choropleth-map

## Tasks

* [ ]

**Comment by rufuspollock** [comment]
@anuveyatsu and I have done analysis on this in some detail and now know what we need (see hackmd data view appendix on this). For now, not an immediate priority so moving to backlog.
