### ISSUE TITLE
Improve the API documentation

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/dpr-api#320]
API docs would benefit from tidying up http://staging.datapackaged.com/apidocs/index.html.

## Acceptance Criteria

* [ ] Good (succinct, understandable grammatically correct) description for all API stuff

## Review

- auth
	- [x] GET `/api/auth/callback`  - 
		-  endpoint accepts no argument, returns 500 in any case https://staging.datapackaged.com/api/auth/callback. 
		- description says: "This ia callback api when we redirect the api to Auth0 or any external" - prob remove
	- [x] GET `/api/auth/login` 
		- description says: "This API is responsible for Login through external auth provider" - simplify
	- [x] POST `/api/auth/token` 
		- description says: "This API is responsible for returning JWT token". 
		-  Email description says "user email id" 
	- [ ] POST `/api/datastore/authorize` description says: 
		- Not clear description - This API is responsible for generate signed urls for multiple file
		- description for data parameter: "publisher name and package name, and file details"
		- datatype for data parameter is unknown
- package
	- [x] GET `/api/package/dataproxy/{publisher}/{package}/r/{resource}.csv DPR resource get operation.`
		-  we don't proxy data any more
	- [x] GET `/api/package/dataproxy/{publisher}/{package}/r/{resource}.json DPR resource get operation.` 
		- we don't proxy data any more
	- [x] POST /api/package/upload
		- data package should be one word everywhere and camelcased - DataPackage  
		- Implementation Notes - " This API is responsible for getting the Data Package (datapackage.json, README) and importing it into our MetaStore."
		- first parameter does not have name, datatype is undefined
		- Authorization parameter has unclear description - Jwt token in format of "{token}. The token can be generated from /api/auth/token"
		- strange reason descriptions for status codes
			- 200 - Data transfer complete
			- 400 - UN-AUTHORIZE
	- [x] GET `/api/package/{publisher}`
		- description says "DPR meta-data get operation"
		- Implementation Notes sys: "This API is responsible for getting All keys for the publisher"
		- model schema says data parameter is list of strings, while it is list of lists
		model schema:
		```
		{
			"data": [
				"string"
			]
		}
		``` 
		actual:
		```
		{
			"data": [
				["string"]
			]
		}
		```
		- first letters for 404 description is lower cased while, 500 capitalized
	- [x] DELETE `/api/package/{publisher}/{package}`
		- unclear Implementation Notes: responsible for mark for delete of data package
		- unclear description for Authorization parameter
	- [x] GET `/api/package/{publisher}/{package}`
		- Unnecessary description for package name
	- [x] PUT `/api/package/{publisher}/{package}`
		- same as for delete
	- [x] DELETE `/api/package/{publisher}/{package}/purge`
		- same as for previous
	- [x] POST `/api/package/{publisher}/{package}/tag`
		- same
	- [x] POST `/api/package/{publisher}/{package}/undelete`
		- same
- search
	- [x] GET `/api/search/package`
                - unclear description [FIXED]
		- parameter "q" ?? [WONTFIX]
		- not clear description for "q"  [WONTFIX] 
- site
	- [x] do we actually need this? This endpoint do not actually have any connection with API. They return pure html  [RMOVED]
## Tasks

- [x] Can we move /api/datastore/authorize into package list because that is where it makes sense?
- [x] API documentation tidy up
  - Not clear descriptions
  - consistency (Capitalized / not capitalized)
- [x] Remove PUT method from API
