### ISSUE TITLE
Check if all core package are published and working fine

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/dpr-api#324]
There are 58 core datapackages that need to be review one by one and be checked whether they are working fine or not. Some of them Eg: https://staging.datapackaged.com/core/ppp is not rendering table as cause of error `Wrong type for header: Year and value:`. Such and possibly other errors might have broken other core data packages.

## Acceptance Criteria

- [x] **ALL** core packages are checked 
- [x] Statuses are documented in spreadsheet
- [x] Common sources of errors are identified

## Tasks

- [x] go through the [list of core datapckages](https://raw.githubusercontent.com/datasets/registry/master/core-list.txt) one by one and check:
	- [x] package page is published (not throwing 404)
	- [x] Tables are working fine 
	- [x] Displays field information for tables
	- [x] Graphs are working fine (if any)
- [x] create spreadsheet and document

### automate this

- [x] get list of packages form dpr-api API
  - [x] check difference with core-list.txt
- [x] loop through the list and check if not 500, 404 etc
- [x] fix  publish command to do data validate as part of what it does
  - [x] Run it and list errors
- [x] Summarize your findings

**Comment by zelima** [comment]
FIXED.
list of core datapackages with error messages and statuses: https://docs.google.com/spreadsheets/d/1vq5dSLyh5vq7M35rk4dC6XvCQ4THvT8cPgAtWDuX1Cw/edit#gid=0

**Comment by zelima** [comment]
Let's automate this!

**Comment by zelima** [comment]
FIXED
We have automated script in https://github.com/frictionlessdata/dpm-py/tree/master/examples
Script tries to publish datapackages and documents the ones that could not be published , by creating the file named `not_published.txt`
After it checks if all published datapackages are fine and working OK, logs in stdout if any of them have problems.

### current outcome

```
30 out of 58 datapackages are published
---------------------------
Following packages have problems after publishing:

https://staging.datapackaged.com/core/geo-nuts-administrative-boundaries | status code: 500
https://staging.datapackaged.com/core/geo-countries | status code: 500
https://staging.datapackaged.com/core/geo-admin1-us | status code: 500
https://staging.datapackaged.com/core/geo-ne-admin1 | status code: 500

```

**Comment by rufuspollock** [comment]
FIXED.

**Comment by rufuspollock** [comment]
@zelima please open a follow up issue (linked from here) to fix these issues and:

* see if logs yield any info about 500 errors)
* summarize what is the problem with the 28 unpublished packages

**Comment by zelima** [comment]
Follow up here https://github.com/frictionlessdata/dpr-api/issues/331

**Comment by rufuspollock** [comment]
500 errors:

* ...

See Issue xxx for the fixing of these.

28 unpublished:

* are all data validation issues: see #331 for a list of them and plans to fix.
