### ISSUE TITLE
[UI] Search page

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#329]
Currently, search page does not look good: https://staging.datapackaged.com/search?q=
We want it to look simple, clear and elegant, e.g.: https://www.npmjs.com/search?q=datapackage&page=1&ranking=optimal

## Analysis

We will implement [NPM example](https://www.npmjs.com/search?q=datapackage&page=1&ranking=optimal) as it looks very simple and information it is displaying very similar and suitable for us. 

Currently, search page's template looks like following:

Here we got title, search box and number of packages found:
```htmlmixed=
<div class="container">
  <div class="col-md-8 pb-4">
    <h1>Search</h1>
    <div id="custom-search-input">
      <form id="search-page-search-form" class="input-group col-md-12" action="/search" method="GET">
        <input id="search-page-search" type="text" class="form-control input-lg" placeholder="Search ..." name="q" value="{{ query_term }}" required/>
        <span class="input-group-btn">
          <button class="btn btn-lg" type="submit">
            <i class="fa fa-search"></i>
          </button>
        </span>
      </form>
    </div>
  </div>
  {% if total_count %}
  <div class="col-md-8 pb-4">
    <h6>{{ total_count }} packages Found</h6>
    <h6>for <b>"{{ query_term }}"</b></h6>
    {{ snippets.search_package_list(datapackage_list) }}
  </div>
  {% endif %}
</div>
```

To make it look like NPM's one:
* have the text with number of packages found in a single line + make it to stand out (colour + font size)
* probably we also could change the title of the page to "Search results" rather than just "Search"

The template for list item (a package):

```htmlmixed=
<div class="card mb-2 card-outline-secondary">
  <div class="card-block">
    <h5 class="card-title">
      <span class="fa fa-files-o"></span>
      {{package.descriptor.title}}
    </h5>
    <h6>[{{ package.name }}]</h6>
    <div class="panel-body">
        {% if package.readme %}
      <p>
      {{ package.readme|truncate(50) }}
      </p>
        {% endif %}
    </div>
    <div class="row show-grid clearfix">
      <div class="col-sm-1">
        <img src="https://avatars3.githubusercontent.com/u/22451011?v=3&s=200" class="img-responsive" />
      </div>
      <div class="col-sm-7 align-self-center">
          <small><a href="/{{ package.publisher_name }} ">by {{ package.publisher_name }}</a></small>
      </div>
      <div class="col-sm-4 pull-right align-self-center">
          <a class="btn btn-secondary" href="/{{ package.publisher_name }}/{{ package.name }}">Explore >></a>
      </div>
    </div>
  </div>
</div>
```

To make it look like NPM's one:
* Use name of the datapackage and make it a link to individual datapackage page
* Next to the name have a publisher name and make it a link to the publisher's page
* As a short description of the datapackage use its title
* What can we use instead of version? Do we have default version?

## Mockup
![image](https://cloud.githubusercontent.com/assets/17809581/24855882/afd932fc-1e04-11e7-85e1-3367ef2c7ab7.png)

## Tasks

- [x] work on single data package holder
  - [x] wrap in a box
  - [x] have header as title of the package, make it bigger
  - [x] have package name underneath, make it as subtitle
  - [x] have number of resources underneath, also small font
  - [x] long extract of Readme as description of the package - text color light gray
  - [x] button on the bottom right
- [x] the page title = "Search result"
- [x] search summary in brand colour, have it inline and larger
- [x] if nothing is found, then have a message about it

**Comment by rufuspollock** [comment]
@anuveyatsu i'd say NPM is great but a little terse! Adding a bit more info is good here. Esp a long extract from the README.

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-api/pull/338
