### ISSUE TITLE
[UI] Improvements and fixes

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#330]
As an outcome from #298 

## Tasks

- [x] credits are missing: OKI, Datopian, Sloan, etc.
- [x] swagger / api spec - recommend we don't consider this v1 yet (I recommend we follow semantic versioning, so we should keep this below v1 for a couple of months at least) @irakli
- [x] page on logout needs a little work #344 
- [ ] ~~metadata button - triggers a download for the DP descriptor - why call it metadata (this is a dp registry, let's keep the terminology consistent)~~ - see #363
- [x] new front-page from mockup (see below)
- [x] new data view page
- [x] footer

![image](https://cloud.githubusercontent.com/assets/17809581/25616660/ed4ca7ce-2f5f-11e7-9c3e-9d6d59fb8aa0.png)

**Comment by zelima** [comment]
FIXED
