### ISSUE TITLE
Improve example packages

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/dpr-api#333]
We have example Data Packages https://staging.datapackaged.com/examples

## Acceptance criteria

- [x] we have few (2-3), but good example data packages that are clear and easy to understand of how to create desired views
- [x] Any new user can easily add desired view to his/her Data Package, by just looking at the example package

## Tasks

- [x] fix-ups according to feedback on existing ones
- [x] Choose 3 example package and make it ideal
  - https://staging.datapackaged.com/examples/simple-graph-spec
  - https://staging.datapackaged.com/examples/geojson-tutorial
  - https://staging.datapackaged.com/examples/vega-views-tutorial
- [x] change titles for packages to be simple and clear - describing what tutorial is for
- [x] nice intro/summary in README
- [x] datapackage.json embedded 
- [x] step by step explaining how to create views for package
- [x] Ask someone to create views for any package according to example data package
- [x] Do the same for all examples

### Feedback on existing ones
* [ ] Typos
* [x] Data Package is 2 words
* [ ] heading should be h2
* [x] script tag (gist) inside README is bad idea cause of security problems
     * allow to embed datapackage.json with new extension 
* [ ] Reasonable titles for example Data Packages, 
    * should be easily understandable that eg: this is vega, this is simple one, this is vega super complex, etc...
* [ ] More description (README) on search page 
* [ ] vega map:
	* we do not support topojson, so no data is displayed for states and not even an error message or something like that.. Eg: "we do not support topo json so data can not be displayed:
	* in resources we should have either name or index, both of them are confusing

**Comment by zelima** [comment]
FIXED 5 example packages created http://datapackaged.com/examples

covering: 

- simple graph spec  http://datapackaged.com/examples/simple-graph-spec
- GeoJson - http://datapackaged.com/examples/geojson-tutorial
- vega graph spec
  - http://datapackaged.com/examples/vega-views-tutorial-topojson
  - http://datapackaged.com/examples/vega-views-tutorial-grouping
  - http://datapackaged.com/examples/vega-views-tutorial-lines
