### ISSUE TITLE
[UI] Publisher Page improvements

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#334]
* don't need to know the 1000 of a second
* want to know how many packages I published.
* who's is this? who is this stuff belongs to?

https://staging.datapackaged.com/core

https://github.com/frictionlessdata

https://www.npmjs.com/~okfn

## Mockup

![image](https://cloud.githubusercontent.com/assets/17809581/24862519/bc568038-1e1e-11e7-9573-02e86ff2b826.png)

## Tasks

- [x] reuse `search` page styles for list of data packages
- [x] fix padding / margin on the top
- [x] fix postition of list of data packages
- [x] fix date format for publisher's joined date
- [x] indicate number of packages that a publisher has
  - at the moment, only showing upto 20 packages
- [x] if there is no packages then have short message saying so

**Comment by anuveyatsu** [comment]
FIXED in  https://github.com/frictionlessdata/dpr-api/pull/338
