### ISSUE TITLE
Logout page needs a little work

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#344]
We need to have very simple message saying that a user is logged out. At the moment, logout page does not have any styles:
![image](https://cloud.githubusercontent.com/assets/17809581/24990687/84f1eb8a-2037-11e7-8ddf-4d518a727cfd.png)

## Acceptance criteria

* [ ] Simple and short message after logged out 
* [ ] Page styling is aligned with other pages 

## Tasks

- [ ] Edit the template accroding to analysis below [10m]
- [ ] Align the styles to fit our site [30m]

## Analysis

Current templage `logout.html`:

```
{% extends "base.html" %}
{% block content %}
<h3>Will see soon</h3>
{% endblock %}
```

Message in the middle of the page and alerting about the action:

<div class="alert alert-success" role="alert">
  You've been logged out successfully.
</div>

Default bootstrap alert message style may not be suitable for our site, so need to do some changes in Sass:

![image](https://cloud.githubusercontent.com/assets/17809581/25473087/d4d3c8c6-2b4f-11e7-9a88-b6d6d39afcc2.png)
