### ISSUE TITLE
Transform data from resources before display in DP view

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#346]
We want to transform data (e.g. pivot, filter) before displaying in a view such as a table or a graph so that we can present the data usefully. E.g.

* Data is often normalised (e.g. year, country, value) and we want it unnormalized (e.g. year, country1, country2, country3 ...)
* Data needs to be filtered to show the right part of the data (or a manageable amount of data)

## Acceptance criteria

* [x] Research what exists and know if we can reuse it and how (esp vega transforms)
  * Have a list of the key transforms *we* want (e.g. pivot, filter)
* [x] Transforms implemented in `datapackage-render-js` library

### Research

* [x] research different kinds of Vega transforms using their docs
* [x] research data transforms library of Vega - https://github.com/vega/vega-dataflow
* [x] research https://github.com/vega/vega-dataflow-examples
* [x] DP Pipelines transforms ... - written up in hackmd analysis

### MVP

* [x] Test using vega dataflow outside of vega to transform data - https://github.com/frictionlessdata/dpr-js/issues/157
  * [x] Specify how to use transforms in DP views and process the data based on this spec
* [x] Integrated into datapackage-render-js https://github.com/frictionlessdata/datapackage-render-js/issues/34

## Analysis

See analysis here:
https://hackmd.io/JwEwjGDMCGBMsFoBsAWAHJBLhmggRgAzCbDDRkgCsAZgKaw35A==?both#vega-transforms

Also there is an issue regarding standalone usage of Vega Dataflows:
https://github.com/vega/vega-dataflow/issues/17

**Comment by rufuspollock** [comment]
@anuveyatsu we don't want to post massive analysis into the description. Plus, that stuff was already in the hackmd on data package views - so let's keep it there. Instead, this issue is lacking tasks and acceptance criteria. I imagine the first task + acceptance criteria would be around researching what's out there we could use and esp vega transforms. Later tasks would then be about implementing the selected solutions.

**Comment by anuveyatsu** [comment]
We've tried out Vega Dataflow separately, next we need to integrate into Datapackage-render-js in the next milestone 22nd May 2017

**Comment by anuveyatsu** [comment]
Closing for now as the most part is implemented. We will create example data packages in #410
