### ISSUE TITLE
Add GitHub Flavoured Markdown extension

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#348]
At the moment, we're using [flask markdown][flask-markdown] to render markdown documents. We want to add a GFM extension so our preprocessor becomes more functional.

## Analysis

There are 2 options:

1) Add extension to our current markdown processor, e.g. using [py-gfm][py-gfm]:
```python
from flaskext.markdown import Extension, Markdown
from mdx_gfm import GithubFlavoredMarkdownExtension

markdown_instance = Markdown(app, extensions=[GithubFlavoredMarkdownExtension()])
```

2) We could replace [flask markdown][flask-markdown] with [misaka][misaka].

After we add GFM support, we may need to have styles for highlighting code - we can use Pygments - https://pythonhosted.org/Markdown/extensions/code_hilite.html

## Tasks

- [x] use option 1 as we've already done some work with `flask-markdown`
- [x]  refactor `app/utils/helpers.py`
- [x] add stylings for highlighting code
- [x] Hand test GFM is working

[flask-markdown]: https://pythonhosted.org/Flask-Markdown/
[py-gfm]: https://github.com/Zopieux/py-gfm
[misaka]: https://github.com/FSX/misaka

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-api/pull/351

**Comment by anuveyatsu** [comment]
We're sanitizing HTML first and then converting to HTML. This causes some bugs, e.g. `>` symbols that used for blockquotes in markdown are escaped so not converted into `<blockquote>` tag. We need to markdownify first and then sanitize HTML.

Also would be a good to implement code highlighting. In fact, `py-gfm` is already adding appropriate tags and classes, all we need to do is to add stylings for those classes.

**Comment by rufuspollock** [comment]
@anuveyatsu please add a separate issue about code highlighting or modify this issue to include.

Good spot re the problem of escaping -- and something I imagine we spotted in tests (if not, we should have a test that would have shown it up and then fix that test).

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-api/pull/352

Test case for markdown's blockquote support - https://github.com/frictionlessdata/dpr-api/commit/11f12fb492544edc021243011fb404cde994c171
