### ISSUE TITLE
Embed HTML-ified DataPackage.json in Rendered README

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#349]
User stories:

As a Potential Publisher I want to see data package descriptor so I can learn how the views on the page are built.

- And how data package descriptors work generally

=>

As a Publisher I want to embed data package descriptor (datapackage.json) in my (rendered) README so that I can comment on it and illustrate specific points (so that others can learn how I built my data package and i can highlight key features)

*As a Publisher I want to embed resources (or snippets of them) in my README so that I can comment on them and illustrate specific points*

*As a Publisher option to show data package descriptor nicely rendered as json in my data package view page so that people can see it and understand how things work*

- More generally, like github, we may want to enrich my README (or other things later like issues) with internal references e.g. `@{publisher}` or `#{issue}` or `@{publisher}/{dataset}/{resource}`

## Acceptance criteria

- [x] passing test for `dp_in_readme()`
- [x] users can pass variables in readme such as: `{{dp}}`, `{{dp.json}}`, `{{datapackage}}`, `{{datapackage.json}}`
- [x] variables are replaced by dp descriptor and rendered in README as json code snippet

## Tasks

- [x] function for analysing README text and replacing variables with DP descriptor as markdown code snippet
- [x] tests for a new function
- [x] refactor controller to replace variables before converting readme into html

## Analysis

```python
import markdown from xxx

def readme_variables_replace(dp):
    dpjson = dpjson_as_html(dp.descriptor)
    ctx = {
        'datapackage.json': dpjson,
        'dp.json': dpjson,
        'dpjson': dpjson
    }
    out = dp.readme
    for key, value in ctx:
        out = out.replace('{{%s}}' % key, value)
    return out

def test_markdown_special():
    out1 = markdown_special("# title")
    expect(out).to_be("<h1>title</h1>")
        
    readme = '''
My incredible data package.

See my datapackage.json, to see how I create awesome views:

{{datapackage.json}}

`{{datapackage.json}}` # should not render as HTML (regex matching {{datapackage.json}} )
'''
    out2 = markdown_special(readme, ctx)
    expect(out2).to_be(
      '''
      <div>
        datapackage.json nicely rendered ... (with line numbers ...)
      </div>
      '''
    )
    
    unsafe_string = "<script>test</script>"
    out_safe = markdown_special(unsafe_string)
    expect(out_safe).to_be("&lt;script")
```

**Comment by anuveyatsu** [comment]
@rufuspollock probably it worth to replace `dpjson` variable with markdown not html. So basically we just wrap json object with markdown code block.

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-api/pull/353
