### ISSUE TITLE
Understand use of datapackage pipelines

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/dpr-api#350]
We want to  use data package pipelines so that we can see where they would be relevant and what it would take to use them.

## Tasks

* [x] Read up on data package pipelines and understand what they are and how they work - what problems do they solve
  - Review meeting docs
  - Review meeting recording
* [x] Read up on and learn about related technologies
  * [x] Docker - TODO: link to notes
  * [ ] queues 

## Analysis

Questions:

* What is the DataHub? What features does it or will it have?
* What are Data Package Pipelines (DPP)
* What are DataHub needs that could benefit from DPP?

**What is the DataHub? What features does it or will it have?**

DataHub is the place where *people* can publish and keep their own data, or find data published by other *people*.

People = data wranglers = those who use machines (e.g. code, command line tools) to work with their data rather than editing it by hand (as, for example, many analysts do in Excel). (Think people who use Python vs people who use Excel for data work)

* Data is not chaotic and is in some sense neat
* Can present your data with various visualization tools (graphs, charts, tables etc.) 
* Easy to publish
* Specific data (power) tools and integrations
  * Can validate your data before publishing
  * Data API
  * Data Conversion / Bundling: zip the data, provide sqlite
    * Generate a node package of your data
  * (Versioning)

Why use DataHub rather than e.g. github or drive or dropbox?
  * Focused on data and focused on power users and their structured datasets
    * Size of data means you can't or don't want to use git  => issues with github
    * Power users: not docs / spreadsheets like dropbox, drive. We are talking about files that are larger and that people want to mainpulate automatically not edit manually.
      * one area of overlap is smaller spreadsheet type stuff
  * Provide specific adaptations for data:
    * Specific tweaks esp around presentation
    * Power tools and integrations
  * Example of github: github is organized around code (from layout of files, to code review etc). Whilst quite a bit is common for power data wrangling, there is quite a bit that is missing e.g.
    * No graphing
    * Metadata not clearly presented
    * Issues previewing data when large or wide
    * ...

**What are Data Package Pipelines (DPP)**

* What is ETL? Ans: extract, transform, load
* What are other well known open source ETL frameworks
  * airflow, luigi, ... 
* What is different about DP Pipelines vs other ETL systems

Key differences between DP Pipelines and other ETL frameworks:

* DPP has simple config - no code. Many other frameworks are code based -  Everything is written in code. Eg: dependent on python, you have to import, define functions etc...
  * DPP is not coder oriented. So non technical, non coders could easily understand how to define different processes, what parameters to set and easily run the whole process. 
* Simple (and limited): only supports tabular data packages

How it works. Two types of operation:

- modify  metadata (datapackage.json)
- or create new data resource
	- number of great features like scraping, join two or more resources, export to zip etc...

Another feature: 

- schedule tasks
- define dependencies 
- dashboard to see statuses that is stored in DB?? 
- You can write your own processes as well 

**Where is DPP relevant for DatahHub? I.E. what are the DataHub needs that could benefit from DPP?**

use case 1:

- a package is pushed
- hits system
- kickoff task that zips and dumps to S3

use case 2:

- have geo code data package live
- want country name added
- implies
  - new data package derived from

use case 3:

- user created a spec herself
- user thereby triggers a pipeline
  - scheduled? on demand?
- output is a data package on disk

use case 4:

- data validation

**Comment by rufuspollock** [comment]
@zelima please:

* Inline from meeting doc the "why" (i.e. what we can use DPP for)
* Create acceptance criteria e.g.
  * Have clear needs identified that DPP address
  * identify a MVP
  * understand what steps would be involved in an implementation of the MVP (created a new epic for this)

**Comment by zelima** [comment]
FIXED see analyzes section above
