### ISSUE TITLE
Design Data Package Pipelines Trial

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#356]
We anticipate Data Package Pipelines can be very useful for performing automated tasks such as scraping and merging -- as well as a demonstration of how to build and deploy async worker infrastructure.

However, as yet we have not used Data Package Pipelines and so we need to:

* Research and understand them better
* Design an MVP trial to test them out and deliver some immediate value

[DPP Meeting document][dpp-doc]

[dpp-doc]: https://hackmd.io/GYNghiAmAsCskFoDGBTAzARgdFlECMlYVskB2WMSNWATjWiSA===

## Acceptance Criteria (for epics or "big" issues)

* [ ] Set out the technical and business case for Data Package Pipelines
* [ ] MVP Plan for usage and integration

## Tasks

* [ ] Research Data Package Pipelines - what are they, how they work
* [ ] Identify DataHub needs where DPP are relevant
* [ ] Design an MVP
