### ISSUE TITLE
Analysis and planning for sprint 8 May 2017

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/dpr-api#361]
Before we add the issues to current milestone, we need to do analysis for them and decide whether we do them in current milestone or no. We need to track time for doing this.

## Acceptance Criteria

* [x] all issues with `Stage: analysis` have proper analysis
* [x] issues moved into current milestone are estimated 

## Tasks

* [x] List out all the issues
* [x] Go through the list and do analysis for all of them
* [x] if issue goes to current milestone estimate it

## Analysis

List of issues

* [x] Transform data from resources before display in DP view  https://github.com/frictionlessdata/dpr-api/issues/346
* [x] Get rid of duplicated roundtrip to authenticate user https://github.com/frictionlessdata/dpr-api/issues/232
* [x] Publisher page is loading for not existing users https://github.com/frictionlessdata/dpr-api/issues/325
* [x] Search does proper FTS over title and maybe README https://github.com/frictionlessdata/dpr-api/issues/327
* [x] Handle datapackage.json that may cause 500 errors https://github.com/frictionlessdata/dpr-api/issues/355
* [x] Design Data Package Pipelines Trial https://github.com/frictionlessdata/dpr-api/issues/356
* [x] Fix core packages that have validation errors https://github.com/frictionlessdata/dpr-api/issues/331
* [x] Design a trial usage of DP Pipelines - "MVP"  https://github.com/frictionlessdata/dpr-api/issues/358
* [x] Better exception handling  https://github.com/frictionlessdata/dpr-api/issues/312
* [x] Remove general logic that is inlined with route handlers https://github.com/frictionlessdata/dpr-api/issues/328
* [x] Improve data package examples #333

**Comment by zelima** [comment]
FIXED
