### ISSUE TITLE
Showcase page: redesign for great UX esp re getting the data

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#363]
Redesign data showcase page for great UX esp re getting the data (download, into R, into python)

**User stories**

showcase page - I want to know who, what, when, how I can get it and use it = download + format

As a Consumer I want to get the data from a package as quickly and easily as possible so that I start using it to generate insight

* Want to download it (in convenient format e.g. CSV or JSON (developers))
* Want to use from R or python (directly if I can)

## Acceptance Criteria (for epics or "big" issues)

* [x] Quick, easy to use download instructions
* [x] Instructions to use from R (in page)
* [x] Instructions to use from python (pandas) (in page)

## Tasks

* [x] New design
  * [x] Theme - first pass
  * [x] Layout tweaks
  * [ ] Font
  * [ ] What metadata to show, where
* [x] Think and analyse how downloading would work from user perspective
  * [x] from the browser
  * [x] into R and Python + implement - #383 

Misc small items:

* [x] metadata button - triggers a download for the DP descriptor - why call it metadata (this is a dp registry, let's keep the terminology consistent)

**Comment by anuveyatsu** [comment]
Screenshots of work so far (re data showcase page):

![image](https://cloud.githubusercontent.com/assets/17809581/25669138/7ee0d684-304a-11e7-9676-b03f989d96ae.png)

**Comment by anuveyatsu** [comment]
Current page layout:

![image](https://cloud.githubusercontent.com/assets/17809581/25791448/379f07d2-33e2-11e7-8fb9-0f5e96f1d69b.png)

**Comment by anuveyatsu** [comment]
FIXED - new mockup implemented + R and Pandas instructions ( #383 )

Current showcase page layout:

![image](https://cloud.githubusercontent.com/assets/17809581/25801517/bbd3d1cc-340f-11e7-8924-eceea2bee3ad.png)
