### ISSUE TITLE
Configurable list of "best" packages to show

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#364]
On the front page, we want to show the best 3 (or more) packages from core publisher + 3 (or more) example packages. We want to have some list and be able to configure it when needed.

## Acceptance Criteria

* [x] Can configure list of "best" packages using `xyz/abc` styling naming (publisher name and package name)
* [x] Can configure list of "tutorial" packages similar to core

## Tasks

* [x] research [45m]
  * [x] research site controllers - how `/search/` page is implemented, how list of packages built and passed to the template [30m]
    * [x] note we don't have to reuse search ...
  * [x] find out which snippet is being used for search results page to show list of data packages [15m]
  * [x] Research how to set config list (do we just hardcode for now in config.py!) What do we do if packages not found (just ignore them then ...)
* [x] Test
* [x] reuse / refactor to use code snippets for front page [30m]

### Refactor Logic Layer

SCQA = situation, complication, question

* Situation: logic for getting a data package in form for use in a template is inline in showcase controller (/publisher/name)
* Complication: we want to use it elsewhere, e.g. for front page sample packages
* Question: what do we do that avoids duplication
* Answer: factor out this functionality into the logic layer.

Plan of action:

* Write a logic test for get_package function
* Refactor getting a data package code from controller into here
* Commit
* Then use same logic in front page with config
    * Write test first

**Comment by anuveyatsu** [comment]
FIXED in #372  and #373
