### ISSUE TITLE
[epic] Overhaul theme and UX of site for alpha launch (May 2017)

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#368]
Do another round on site UX and have everything working (=> hiding/removing things that are not yet working well enough like publishing).

## Acceptance Criteria (for epics or "big" issues)

* [x] Site looks awesome
* [x] Nothing left that is not working

## Tasks

* [x] showcase page - #363
* [x] Front page @shiewie @anu
  * [x] Redesign
  * [x] Show Best packages and Examples packages - #364
    * [x] Tidy up examples @irakli @meiran - #333 
  * [x] Publishing section (and explain it is coming soon)
    * [x] Design @shi
* [x] Theme
  * [x] Navbar - change the links
    * [x] Find data search box should just be a link
    * [x] API should move into footer (if it is anywhere) - not relevant for most users
    * [x] Sign in / sign up should be redirected in some way (see below on disable publishing stuff)
  * [x] Footer - with logos
* [x] Disable publishing stuff
  * [x] Disable sign up
    * A: Just hide it all!
    * ~~B: redirect to "give us your email" info (probably on front page down below ...)~~
* [ ] About section (low priority)
  * Explain what this is, who is behind it etc
* [x] General UI - https://github.com/frictionlessdata/dpr-api/issues/330
* [x] Search page #375

**Comment by anuveyatsu** [comment]
FIXED - browse the website for current look:
https://staging.datapackaged.com/

**Comment by anuveyatsu** [comment]
Current website look:

![image](https://cloud.githubusercontent.com/assets/17809581/25805239/dfc6928e-3420-11e7-94ee-9c119f97dd03.png)
