### ISSUE TITLE
New design for Search Page

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#375]
We want Search Page to be aligned with general site design and theme.

## Acceptance Criteria (for epics or "big" issues)

* [ ] to look similar as the mockup
* [ ] everything is working on the page (buttons etc.)

## Tasks

*Task list for a non-epic issue*

* [x] create a mockup - see below [2h]
* [x] implement mockup [2h]
  * [x] merge with previous design - keep key information such as search summary etc.

Additional tasks after review:

* [x] get rid of the box outline
* [x] get the cube smaller
* [x] get rid of the explore button
* [x] do not have the grey outline(badges) around the number of resources
* [x] name resource as file
* [x] have the by…. right under the Title
* [x] revert color to original

![image](https://cloud.githubusercontent.com/assets/17809581/25692038/961a9d4a-30c1-11e7-97a0-0f77b33cdd93.png)

**Comment by anuveyatsu** [comment]
@rufuspollock can you please take look at this. Without borders, it does not look great. Also, I am not sure about the background color - see the second screenshot below. I think must be as neutral as possible - keeping white would be better IMO.


![image](https://cloud.githubusercontent.com/assets/17809581/25693524/92044d78-30cb-11e7-8db9-52ced1d34621.png)

![image](https://cloud.githubusercontent.com/assets/17809581/25693693/8186e2ca-30cc-11e7-95a7-a012eab18527.png)

**Comment by anuveyatsu** [comment]
Updated with new background color:

<img width="1280" alt="screen shot 2017-04-30 at 23 27 59" src="https://cloud.githubusercontent.com/assets/17809581/25699454/0b76cf1e-30e5-11e7-8814-6c4e1e4b597e.png">

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-api/pull/379

Current layout:

<img width="1280" alt="screen shot 2017-05-04 at 22 58 21" src="https://cloud.githubusercontent.com/assets/17809581/25715451/4c956f4a-311d-11e7-9e93-3b6c9eb82db8.png">
