### ISSUE TITLE
[ux] Showcase page improvements

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#388]
After reviewing Data Showcase Page on 8 May 2017, we have received several reasonable feedbacks that should be fixed.

## Acceptance Criteria

* [ ] All points from feedback are considered and fixed

## Tasks

* [x] Descriptor should be separated from download. It is much less important. I’d put it in the key info (and probably give it its full name likke “Data Package Descriptor (JSON)”)
* [x] Work on list of formats in this package
* [x] The home page link and other link need to be clarified a bit (in key info) - at least in vega case having home page point to the page you are on is a bit weird but might make sense
* [x] Download button on left should be on its own and even more prominent
  * [x] Check with Sylvie
* [x] Think about having resource summary in LHS bar - i.e. a short list of the main files and download option there straight away (you could have an info link that moved you down the page if you wanted)
* [ ] Each data file section need to somehow be more cleanly indicated
  * that task is probably irrelevant after we've moved Data files to LHS bar. 
* [x] "by examples” under title should just have example linked to examples publisher (by should be outside the link
* [x] get “smooth” scrolling on all pages to anchor links (front page and this page)

Feedback from Sylvie (phase 1):

* [x] borders for buttons in instructions nav tabs - so it is clear they are buttons
* [x] Get data -> Data files
* [x] headings - two versions:
  * [ ] Large section have little cube next to tittle +// Small section smaller type case
  * [x] Large section are in green. // Small section smaller type case + color violet
* [x] remove message section from form on the front page

Feedback from Sylvie (phase 2):

* [x] on LHS bar
  * [x] DATA FILES -> DOWNLOAD FILES

## Additional tasks that are not included in estimates

* [ ] Have an example where you had “sources”
* [ ] we also want straight under the title and byline something like “Download or use from Python, R, Pandas, Javascript or …” and have each part linked.
  * [ ] Discuss with Sylvie and get design

**Comment by anuveyatsu** [comment]
@rufuspollock re: list of formats, can you please take a look at screenshot below. Colours are default ones for now:

<img width="304" alt="screen shot 2017-05-09 at 16 45 57" src="https://cloud.githubusercontent.com/assets/17809581/25847253/2171157c-34d7-11e7-90e6-80dff6548136.png">

**Comment by anuveyatsu** [comment]
Mostly FIXED - closing this issue for now as after discussion with Sylvie we did not have more things to do. The screenshot of current look is below:

![image](https://cloud.githubusercontent.com/assets/17809581/25957887/1fe8f0c4-3691-11e7-8856-88b340580859.png)
