### ISSUE TITLE
Pygments style highlighting on code blocks 

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#389]
Currently, our code blocks on showcase page are not highlighted according to its language. The highlight would ease reading of the code snippets, so we want to implement Pygments style highlighting here.

![image](https://cloud.githubusercontent.com/assets/17809581/25836641/573c2e80-34aa-11e7-8c96-fd79cf6e1ae3.png)

## Acceptance Criteria

* [x] Code blocks in the instructions are highlighted
* [x] Code blocks in the README are highlighted

## Tasks

* [x] find out how our markdown preprocessor converting Markdown code blocks into HTML
  * [x] probably will need to move html code blocks for instructions from here to controllers / utils
* [x] generate Pygments styles accordingly
* [x] check everything is working

**Comment by anuveyatsu** [comment]
FIXED in https://github.com/frictionlessdata/dpr-api/pull/396

In instructions:
![image](https://cloud.githubusercontent.com/assets/17809581/25935826/c3d3eedc-3646-11e7-99c5-f12d130b87ac.png)

In README:
![image](https://cloud.githubusercontent.com/assets/17809581/25935851/df64144c-3646-11e7-847c-b91d91de112d.png)
