### ISSUE TITLE
Error on getting Data Package from https request

### ISSUE THREAD

**Issue by Mikanebu** [frictionlessdata/dpr-api#390]
Importing Data Package using datapackage-py library comes with an error when we use SSL connection. Only works for http request. Error displayed: 
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Zhiyenbayev_mirza/Desktop/R_coding_space/env3/lib/python3.5/site-packages/datapackage/resource.py", line 304, in iter
    headers=1, encoding=encoding, **options).open()
  File "/Users/Zhiyenbayev_mirza/Desktop/R_coding_space/env3/lib/python3.5/site-packages/tabulator/stream.py", line 219, in open
    self.__parser.open(self.__source, self.__encoding, self.__loader)
  File "/Users/Zhiyenbayev_mirza/Desktop/R_coding_space/env3/lib/python3.5/site-packages/tabulator/parsers/csv.py", line 55, in open
    self.__chars = loader.load(source, encoding, mode='t')
  File "/Users/Zhiyenbayev_mirza/Desktop/R_coding_space/env3/lib/python3.5/site-packages/tabulator/loaders/web.py", line 45, in load
    raise exceptions.HTTPError(str(exception))
tabulator.exceptions.HTTPError: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645)>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_pandas.py", line 5, in <module>
    storage = datapackage.push_datapackage(data_url, 'pandas')
  File "/Users/Zhiyenbayev_mirza/Desktop/R_coding_space/env3/lib/python3.5/site-packages/datapackage/pushpull.py", line 52, in push_datapackage
    data = resource.iter()
  File "/Users/Zhiyenbayev_mirza/Desktop/R_coding_space/env3/lib/python3.5/site-packages/datapackage/resource.py", line 308, in iter
    six.raise_from(ValueError(msg.format(data_path_or_url)), e)
  File "<string>", line 2, in raise_from
ValueError: Data at 'https://bits-staging.datapackaged.com/metadata/core/house-prices-us/_v/latest/data/cities-month.csv' isn't in a known tabular data format
```

## Acceptance Criteria

* [ ] Imports data without an error from Python2
* [ ] Imports data without an error from Python3

## Tasks

*Task list for a non-epic issue*

* [ ] Check from other sources such github datasets etc. 
* [ ] Check Security requirements

## Analysis

- *Successfully imported same dataset from github datasets page 'https://raw.githubusercontent.com/datasets'*
- *Tested with http request(without SSL) - it worked fine*
- *Installed requests[security] according to this link 'https://github.com/frictionlessdata/dpm-py/issues/94'*
- *Followed instruction on using **datapackage** https://pypi.python.org/pypi/datapackage/1.0.0a4*
- *Used different version of **request, datapackage, pyopenssl, openssl, cryptography**.*
