### ISSUE TITLE
Can switch over data.okfn.org/data to this site

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#397]
We can switch over data.okfn.org to this new datahub so that users of data.okfn.org benefit from all the improvements in the new site including much greater reliability (old site now has timeouts on data access quite often), better graphs, more elegant and better ux on showcase.

## Acceptance Criteria

* [ ] Stable domain we can redirect and redirection for both pages and for resource links
* [ ] Showcase page works
* [ ] All core datasets
* [x] Usable frontpage for site
* [ ] Solution for tools pages on old site (either drop or recreate - tools/view tools/validate)

## Tasks

* [ ] Domain and redirection
  * [ ] Stable domain we can redirect to @rufuspollock
  * [ ] Redirection for both pages and for resource links
* [ ] Showcase page works - #388 
* [ ] All core datasets - #331 
* [ ] JSON data versions as well as CSV
* [x] Usable frontpage for site
* [ ] Solution for tools pages on old site - tools/view tools/validate exist
