### ISSUE TITLE
Move logic from models into logic layer

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/dpr-api#401]
Currently we are using static methods in models for creating / getting / updated / deleting stuff from db (models). We need this to be moved into logic layer where it belongs and keep models as simple as possible 

## Acceptance Criteria

* [x] No logic in models
* [x] logic layer is organized and easily understandable  

## Tasks

* [x] move/update tests for static methods of models in the logic test part [1]
* [x] move functions from models to logic and delete stuff if appropriate [2]
* [x] update imports in code base as necessary
* [x] move database logic from logic `__init__ .py` into  `db_logic.py` [1.5]
* [x] move Bitstore in separate module `app/bitstore.py` [1]
* [x] move tests for bitstore [1]
* [x] rename `auth/models` to `auth/jwt` and refactor [0.5]

**Comment by zelima** [comment]
FIXED
