### ISSUE TITLE
Show download and page views stats in the UI

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#407]
As soon as we have dp download and page view stats in our database, we want to show numbers for publishers and users.

## Acceptance Criteria

* [ ] On Showcase Page:
  * [ ] I can see total number of downloads
  * [ ] I can see number of downloads for the last week
  * [ ] I can see total number of downloads for individual resource
* [ ] On package summary (this includes front, search and publisher pages):
  * [ ] I can see total number of views of the package page
  * [ ] I can see total number of downloads
  * [ ] I can see number of downloads for the last week

## Tasks

* [ ] mockup
  * [ ] showcase page
  * [ ] package summary
* [ ] ...

## Analysis

Download button under each resource:

<img width="171" alt="screen shot 2017-05-13 at 12 50 02" src="https://cloud.githubusercontent.com/assets/17809581/26023432/00d95da2-37dd-11e7-9d9f-2626dfda0a93.png">
