### ISSUE TITLE
Create example Data Packages for data transforms

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#410]
Recently, we have added a feature to transform data before rendering on the showcase page. We want to have example Data Package for each transform we are supporting + one with combined (several transforms for one dataset) transforms.

## Acceptance Criteria

* [x] example data packages for each transform with clear instructions on the live site

## Tasks

* [x] example for filter
* [x] example for aggregate
* [x] example for formula
* [x] example for sample

**Comment by anuveyatsu** [comment]
FIXED but still some work remains here https://github.com/frictionlessdata/datapackage-render-js/issues/36

Example packages:
Filter and Formula: https://staging.datapackaged.com/examples/transform-examples-on-co2-fossil-global
Aggregation: https://staging.datapackaged.com/examples/transform-example-gdp-uk
Sample: https://staging.datapackaged.com/examples/example-sample-transform-on-currency-codes
