### ISSUE TITLE
Refactor response for getting metadata API

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#412]
Following API requires improvements into its response: "`/api/package/{publisher}/{package}` -
DPR meta-data get operation". There is a typo in `datapackag_url` but we also want to rename it. Also we want to remove `views` property from the top level as it is already in descriptor.

http://staging.datapackaged.com/api/package/core/finance-vix

## Acceptance Criteria

* [x] response has `bitstore_url` with value as `.../_v/latest`
* [x] response has not `views` in top level

## Tasks

* [x] fix `datapackag_url` => `bitstore_url: ..._v/latest`
  * [x] rename `datapackag_url` => `bitstore_url`
  * [x] remove datapackage.json from the url
* [x] remove views from the top level object
* [x] change the upload url for datapackage.json (remove datapackage.json from the end)

**Comment by zelima** [comment]
Currently dpm publish does not work - throws 500 as we need to change upload URL from `.../lates/datapackage.json` to `.../latest`

**Comment by zelima** [comment]
FIXED. if relative path to file ends with datapackage.json it is replaced with empty string (`''`)

**Comment by anuveyatsu** [comment]
This issue was misunderstood:

* [x] we still want to have actual `datapackage.json` on `.../_v/latest/datapackage.json`
* [x] refactor DPR js appropriatelly 

At the moment, we are not getting `datapackage.json` from above uri, which is crucial for our service to operate.

**Comment by zelima** [comment]
FIXED
