### ISSUE TITLE
Need titles for views

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/dpr-api#415]
We need titles for table views - use view's title. At the moment we don't have any titles there. This issue will be fixed in `dpr-js` and `datapackage-render-js` libraries.

## Acceptance Criteria

* [ ] when I arrive at the showcase page I am clear about each view

## Tasks

* [x] https://github.com/frictionlessdata/dpr-js/issues/162
* [x] https://github.com/frictionlessdata/datapackage-render-js/issues/38

**Comment by zelima** [comment]
FIXED
