### ISSUE TITLE
Core data packages failed validation in the frontend

### ISSUE THREAD

**Issue by Mikanebu** [frictionlessdata/dpr-api#418]
Some core data packages failed validation in the frontend. Preview is not working in showcase page

## Acceptance Criteria

* [ ] Preview in showcase page works fine
* [ ] Validation passes in the frontend

## Tasks

* [ ] Fix packages in the upstream where it can be fixable
* [ ] Analyse data packages validation in the dpr-js for string type

## Analysis

    Analysed 57 core data packaged which are published in the staging.datapaged.com. 
* 17 core data packages have an error in the showcase page. Preview is not working 
Error messages are related to the type property in the schema(metadata).
Somehow when "type"="string": validation gives an error for numbers like: 17, 1.5 etc. 
Probably js validation has a bug since it cannot accept numbers. 
The list of core data packages can be found in the following spreadsheet:
https://docs.google.com/spreadsheets/d/14kJluhePaMOx6vYBic0poVjDYK3I8-v_xF3sv4Focac/edit#gid=1881654332
