### ISSUE TITLE
Update production database structure(s)

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/dpr-api#419]
We have modified database structure for getting datapackage.json and README in #411. Live staging and production databases on RDS needs to be updated as well. 

## Acceptance Criteria

* [ ] DB structure is updated
* [ ] All packages are still published

## Tasks

* [ ] re-created db with `manager.py` on RDS for staging and production [0.25]
* [ ] re-publish core packages [0.25]
* [ ] re-publish example [0.5]

**Comment by zelima** [comment]
FIXED
