### ISSUE TITLE
Get login button back in navbar

### ISSUE THREAD

**Issue by zelima** [frictionlessdata/dpr-api#420]
We need login button in navbar back

## Acceptance Criteria

* [ ] User is able to login with github account

## Tasks

* [x] comment out the part for login button from codebase
* [x] Test (try and actually sign up)

**Comment by zelima** [comment]
FIXED works if logged in from https. Further discussions in #422
