### ISSUE TITLE
[super] Signup Flow

### ISSUE THREAD

**Issue by rgrp** [frictionlessdata/dpr-api#6]
- [x] Sign up button in frontend - main page and navbar
- [x] Register basic identity - **external: auth0**
  - [x] Verify identity - **external: auth0**
- [x] Complete profile: username, full name (**external: auth0**)
- [x] Local "on new user" actions: Handle callback from external auth provider and perform "on new user" actions #9
  - [x] Create user object in local DB
  - [x] Create secret key (for command line tools etc)
  - [x] Create publisher and associate user as owner - #66 + #9 
  - [x] Issue them a token so they are signed in
- [x] Redirect to dashboard (perhaps special flash message for new users!)
- [x] Send welcome email _in background_ #10
- [x] Test "end to end" (mocking out external stuff) #11

_What do we do if successful external auth signup but failure locally so no local user - i.e. we are in inconsistent state?_
### Key Steps and Implementors

<img src="https://docs.google.com/drawings/d/1HfrrDw5HKaQcz48PjYyBzy6XWTqAtyX0ZAIJs0m5OXc/pub?w=781&h=655" />
### Technical Flow

<img src="https://docs.google.com/drawings/d/1XTZKVHlkhzBsm92Vo8u6yF__TMqXN6ZDZ-DKhVPDmWM/pub?w=670&h=661" />

**Comment by Fak3** [comment]
Summarizing everything a learned about jwt so far - is is a terrible idea to use it for front-end app sessions. Most points are captured in the blogpost: https://www.reddit.com/r/node/comments/4nwmv1/stop_using_jwt_for_sessions/
I would recomment using flask sessions for frontend and jwt only for api.

**Comment by rgrp** [comment]
FIXED. All sub-items now done.
