### ISSUE TITLE
[epic] Publisher Page

### ISSUE THREAD

**Issue by rufuspollock** [frictionlessdata/dpr-api#80]
US: As a Consumer I want to see a publisher’s profile so that I can discover their packages and get a sense of how active and good they are 

As a Publisher I want to have a profile with a list of my data packages so that:
- Others can find my data packages quickly and easily
- Can see how many data packages i have
- **I can find a data package i want to look at quickly [they can discover their own data]**
- **I can find the link for a data package to send to someone else**

## Tasks

* [x] Design page #79 
* [x] Implement page in frontend using mocks - covered in items in this epic https://github.com/frictionlessdata/dpr-js/issues/53
* [x] Implement Publisher info API #202 
* [x] Implement API to get publisher packages - part of search epic #200 
* [x] Use this in frontend - https://github.com/frictionlessdata/dpr-js/issues/58

## Analysis

Key features

* Publisher details
  * Title and username
  * Picture
  * When they joined
  * *[Short description text (how is this set? We don't have a profile editor atm)]*
* List of packages
* Members - list users who are members (all public by default atm)

Questions:

* Do we implement UI in Flask or React
* Decide re showing private packages. [if got jwt we can determine it is member/owner of the publisher]. Then we do not  filter the ```packages``` result set, show all packages with tag private.

### Publisher API {1}

API
```javascript=
GET /publisher/{name}

//Response

{
    "name": "",
    "description":"",
    "packages": [
        {
            "name": "package1",
            "description": "",
            "private": true
        },
        {
            "name": "package2",
            "description": "",
            "private": false
        }
    ],
    "members": [
        {
            "name": "mem1",
            "role": "member"
        },
        {
            "name": "mem2",
            "role": "owner"
        }
    ]
}

```

### Page Architecture (if we use ReactJS)

**Design in React:**
Publisher profile will be live in:
```javascript=
<Route path="/:name" component={PublisherProfile}/>
```
```PublisherProfile``` component will hold the whole page

**PublisherProfile:**

Publisher profile is mostly data presentation component.
Thie Component will have two children component
- PackageList
    - PackagePreview
        - Description [first 200 letter]
        - Name
        - Build passing or not [right now mock]
        - Private/ Public [mock right now]
- UserList
    - UserPreview
        - Full Name
        - Gravatar
        - Role

#### API
/api/profile/publisher/<name>
Response:
```
{
  "title": "", //like display name
  "joined":"",
  "writeup:"some details writeup about the publisher",
  "contact": {
   "email":"someone@some.com",
   "phone":"1234-1111" 
  },
  "country": "somewhere on earth" 
}
```

**Comment by subhankarb** [comment]
FIXED.
The url is https://staging.datapackaged.com
